### PR TITLE
Allow duplicate name modules and small fixes

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
Fixes: 
* Move bind command 
* Nametags settings category fix

### CODE REVIEW

**Comment by seasnail8169** [comment]
bruh

**Comment by ThebestkillerTBK** [comment]
> bruh

now the meteor website is down again :skull:

**Comment by I-Got-You-Dead** [comment]
Pain

**Comment by seasnail8169** [comment]
@ThebestkillerTBK are you in the meteor discord?

**Comment by ThebestkillerTBK** [comment]
yeah

**Comment by seasnail8169** [comment]
> yeah

what's your username?

**Pull request closed without merging**
