### PR TITLE
Don't send meteor agent to Mojang

### PR DESCRIPTION
**Pull request by FlorianMichael**
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

This pull request removes Meteor sending the Meteor UserAgent in API requests to Mojang, which is pretty stupid because you could easily detect and block Meteor users that way.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by arlomcwalter** [comment]
??? why would mojang block requests with that user agent

**Comment by Talhoid** [comment]
agree with seasnail

**Comment by allinkdev** [comment]
> ??? why would mojang block requests with that user agent

Imagine how easy it would be for Mojang/Microsoft, if they so wanted to, to permanently ban every Meteor client user who has ever logged into their Microsoft account with the built-in alt manager, by using the conveniently provided "Meteor Client" user agent you currently use to communicate with their authentication server.

**Comment by FlorianMichael** [comment]
I just don't think it's good that a cheat mod tells the official servers of the game creator when it makes API requests.

**Comment by arlomcwalter** [comment]
> > ??? why would mojang block requests with that user agent
> 
> 
> 
> Imagine how easy it would be for Mojang/Microsoft, if they so wanted to, to permanently ban every Meteor client user who has ever logged into their Microsoft account with the built-in alt manager, by using the conveniently provided "Meteor Client" user agent you currently use to communicate with their authentication server.

ok but literally what reason do they have to do that

**Comment by arlomcwalter** [comment]
> I just don't think it's good that a cheat mod tells the official servers of the game creator when it makes API requests.

ok but meteor is not a cheat mod so mojang wouldn't care

**Comment by FlorianMichael** [comment]
It's your choice, I already see Meteor as a cheat client because it has modules for it, but if you see it differently, that's fine.

**Comment by FlorianMichael** [comment]
I just don't think it's a good idea to tell Mojang that you're using Meteor, I mean Meteor is also spoofing the ClientBrand to "vanilla", so you could make the same argument.

**Comment by Talhoid** [comment]
:bruh:

**Comment by arlomcwalter** [comment]
new information has come to light :troll:

**Comment by FlorianMichael** [comment]
That's what I originally wanted to do, but I wasn't sure if the MeteorClient user agent had any function.

**Comment by FlorianMichael** [comment]
done @arlomcwalter

**Pull request merged**
