### PR TITLE
Some changes with ca, noslow, autocity & anchoraura

### PR DESCRIPTION
**Pull request by supakeks**
CrystalAura: Attack Frequency (This is good on NCP servers that have a hard limit on how many PlayerInteractEntityC2SPacket packets you can send in 1 second)

NoSlow: Fixed web timer not resetting the timer in some cases

AutoCity: Auto Switch (I made it a setting since someone may wanna wait until the block can be broken to auto switch with packet mine, this can be good to make it look like you're not citying a player)

AnchorAura: Made it place in liquids (it can be broken inside water/lava)

### CODE REVIEW

**Comment by blendifyClient** [comment]
add that seasnail

**Comment by RedCarlos26** [comment]
We need this

**Comment by MineGame159** [comment]
Why are you changing every setting

**Comment by supakeks** [comment]
> Why are you changing every setting

in ca? since everytime you make a new setting it only indents once instead of twice like before so I just changed ca settings to do that since I assume every other module's settings are gonna be changed too

**Comment by RickyTheRacc** [comment]
Please merge this I'm begging

**Comment by RedCarlos26** [comment]
Yes

**Pull request merged**
