### PR TITLE
Added option for only showing exposed ores with xray

### PR DESCRIPTION
**Pull request by VolcanoCookies**
Added option to xray module to only show exposed blocks. Those that have at least one neighbor that is non-opaque.

### CODE REVIEW

**Comment by MineGame159** [comment]
Isn't Xray's whole point that it displays hidden blocks?

**Comment by VolcanoCookies** [comment]
I find this useful in situations where you for example cannot break blocks for any reason but can interact with them. 
With the new massive caves it can also be quicker to run to exposed ores and mine them rather than digging into deepslate to get hidden ones.

_Also, broken build due to wrong java version?_

**Comment by arlomcwalter** [comment]
also would show ores with any non opaque block next to it, its not quite the same as being exposed

**Comment by VolcanoCookies** [comment]
True, but in natural generation that almost always means its in a cave/surface, assumed doing more than a simple check like this would be rather detrimental to performance.
Should maybe rename it through?

**Comment by MineGame159** [comment]
Could you change the `isExposed(BlockPos)` method to be more efficient and not create new `BlockPos` for every neighbour, basically have a global `BlockPos.Mutable` field that you just change the position of instead of calling `.offset()`.

**Comment by VolcanoCookies** [comment]
This should do it?

**Pull request merged**
