### PR TITLE
Removed useless square-rooting

### PR DESCRIPTION
**Pull request by DAMcraft**
## Type of change

- [x] Bug fix
- [x] New feature

## Description

Calculating sqrt is an operation that requires a lot of resources. As Double.compare only compares two numbers, we don‘t need to calculate the sqrt, as the square of whatever that number is is always bigger as well. 

(example)
sqrt(4) > sqrt(9) 
can be converted into
4 > 9

in other words,
if sqrt(x) > sqrt(y), then x > y
if sqrt(x) < sqrt(y), then x < y
if sqrt(x) == sqrt(y), then x == y

So, dont sqrt if it isnt needed, as computers need to calculate a lot

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by DAMcraft** [comment]
Made a typo in the commit message, meant sqrt(9), not sqrt(0)

**Review by DAMcraft — COMMENTED** [review]
Made a typo in the commit message, meant sqrt(9), not sqrt(0)

**Comment by RacoonDog** [comment]
instead of casting and using double compare, you can just use int/long compare now

**Comment by DAMcraft** [comment]
> instead of casting and using double compare, you can just use int/long compare now

honestly i edited this on my phone, just wanted to add casting to ensure nothing gets bronked

**Comment by RacoonDog** [comment]
> > instead of casting and using double compare, you can just use int/long compare now
> 
> honestly i edited this on my phone, just wanted to add casting to ensure nothing gets bronked
> 
> there is a good possibility this doesn’t even work 👍

54ED3E1F-301B-45C8-ADB4-5E8D9C661D7E
:shock:

**Pull request merged**
