### PR TITLE
Refactor ticking block render into RenderUtils

### PR DESCRIPTION
**Pull request by StormyBytes**
Idea originated from #donator-chat 
https://discord.com/channels/689197705683140636/713429344135020554/1035102740982018069

### CODE REVIEW

**Comment by Wide-Cat** [comment]
might want to take a look at nuker as well because i think it uses a similar rendering mode

**Comment by StormyBytes** [comment]
> might want to take a look at nuker as well because i think it uses a similar rendering mode

done

**Comment by MineGame159** [comment]
Have you even tried running it? Lol. All of the methods you added need to be static.

**Comment by MineGame159** [comment]
For the love of god please fucking test your changes.

**Pull request merged**
