### PR TITLE
Changes sendMessage mixin location

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**

### CODE REVIEW

**Comment by seasnale** [comment]
looks fine, why did you do this tho?

**Comment by ThebestkillerTBK** [comment]
> looks fine, why did you do this tho?

Macros wont work if the mixin is inside chatscreen

**Comment by MineGame159** [comment]
Macros work just fine for me

**Comment by ThebestkillerTBK** [comment]
image
its not working when use meteor commands

**Comment by MineGame159** [comment]
Oh.

**Pull request merged**
