### PR TITLE
Custom font with Nametags module

### LINKED ISSUE #3066: Custom font option nametags
### Describe the feature

Add an option "Custom font" to nametags instead of being linked to the hud.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

### PR DESCRIPTION
**Pull request by Jaranamo1**
## Type of change

- [ ] Bug fix
- [x] New feature

## Description

Allows users to choose custom font with Nametags module
without changing clickgui font

## Related issues

Mention any issues that this pr relates to.
- Closes #3066

# How Has This Been Tested?
- Tested on a cpvp server
- Tested on singleplayer with lots of entites

Videos or screenshots of the changes if applicable.
image

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by BDARmech** [comment]
This is probably insert a hook into the C update feeds. I'd say umm...no.

**Comment by Wide-Cat** [comment]
> This is probably insert a hook into the C update feeds. I'd say umm...no.

what?

**Comment by WERooo** [comment]
can u do it for EntityOwner too?

**Comment by Jaranamo1** [comment]
Probably

**Comment by Jaranamo1** [comment]
> can u do it for EntityOwner too?

I have a implementation but idk if it's worth another pr or smth

**Comment by WERooo** [comment]
> > can u do it for EntityOwner too?
> 
> I have a implementation but idk if it's worth another pr or smth

also need to release texture of previously initialized textrenderer i think

**Comment by Jaranamo1** [comment]
Should be good now

**Comment by WERooo** [comment]
> Should be good now

if text is null getFont will throw NullReferenceException

**Comment by Jaranamo1** [comment]
Thanks, I've added the null check + removed the unnecessary cast

**Pull request closed without merging**
