### PR TITLE
Notebot Refactoring, Song GUI and Bug Fixes

### LINKED ISSUE #2745: Crash on Modpack "Better MC" because ArrayIndexOutOfBoundsException in NotebotUtils
### Describe the bug

Crashing at the last stage of startup.
The error is:
[java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
	at meteordevelopment.meteorclient.utils.notebot.NotebotUtils](https://paste.ee/p/toeBp#:~:text=java.lang.ArrayIndexOutOfBoundsException%3A%20Index%2017%20out%20of%20bounds%20for%20length%2017)

**Java install**
[crash-2022-09-11_12.35.39-client.txt]
Eclipse Temurin JRE with Hotspot 18.0.2+9 (x64)

### Steps to reproduce

```bash
launching the game. 
(MultiMC with Modpack Better MC)
```

### Link to crash report/log if applicable
[crash-2022-09-11_12.48.22-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9542308/crash-2022-09-11_12.48.22-client.txt)

### Meteor Version

meteor client v0.5.1 build #1622

### Minecraft Version

1.19.2

### Operating System

Windows 11 22H2 Build 22000.918

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

### PR DESCRIPTION
**Pull request by EpicPlayerA10**
### Refactoring
- Replaced every `Map<A, List<B>>` with `MultiMap<A, B>`
- Created shared `Song` and `Note` class across different decoders
- Added `SongDecoders` to easily add new song decoders
- Renamed `NullableInstrument` to `OptionalInstrument`
- Added `Notebot#updateStatus` for easier updating text status
- maybe also something that i forgot to write here
### Features
- New Song GUI with Search Bar!
- Moved Random Song button to Song GUI
- Improved noteblocks recording
- Added a tab-complete in `.notebot play (song)` and `.notebot preview (song)`
### Bug fixes
- Fixed #2745
- Fixed bug where noteblock can't be hit while player was in GUI

### CODE REVIEW

**Comment by MineGame159** [comment]
I would remove the horizontal separators between the songs in the selector GUI as it doesn't match other GUIs in the client. Other than that looks good 👍

**Comment by EpicPlayerA10** [comment]
I added these separators because my Song GUI is too wide and sometimes i press wrong button
image

**Comment by MineGame159** [comment]
Yeah, I see what you mean but I just don't like how it is not consistent. Idk. There should probably be some more standard way to create lists that for example slightly lighten up the element you are hovering over or something.

**Comment by MineGame159** [comment]
I guess the separators are fine. Atleast remove the separator that shows up after the last song. And maybe move the one thats between the random button and the search bar to be below the search bar (idk if that would actually look better).

**Comment by EpicPlayerA10** [comment]
Done

**Pull request merged**
