### PR TITLE
Adding waterlogged status to LookingAt module in HUD

### PR DESCRIPTION
**Pull request by flaxeneel2**
This commit implements the suggestion #821 , adding a setting to allow viewing of the block status, if the block is waterlogged or not.

### CODE REVIEW

**Comment by flaxeneel2** [comment]
Oops forgot the screenshots.

Screenshots:
image
image
image

**Comment by seasnail8169** [comment]
just make it say `Birch Slab (Waterlogged) [-83, 75, -18]` if it is and `Birch Slab [-83, 75, -18]` if not

**Comment by flaxeneel2** [comment]
> just make it say `Birch Slab (Waterlogged) [-83, 75, -18]` if it is and `Birch Slab [-83, 75, -18]` if not

Okay, I'll do that, a moment

**Comment by flaxeneel2** [comment]
New screenshots:
image
image

Like that?

**Pull request merged**
