### PR TITLE
ModMenu integration and AntiInvisibility

### PR DESCRIPTION
**Pull request by JFronny**
Adds a ModMenuApi impl that opens the config screen (useful for configuring things without joining a world) and a simple module that reenables rendering for invisible entities

### CODE REVIEW

**Comment by MineGame159** [comment]
You can open the gui in main menu the same way as you would in-game.

**Comment by JFronny** [comment]
What about the other half of this PR?

**Comment by MineGame159** [comment]
If you separate it then I guess its fine.

**Comment by JFronny** [comment]
Separate as in new PR? The relevant commit is already separate from the modmenu commit

**Comment by MineGame159** [comment]
Yes, I can't merge only some commits.

**Pull request closed without merging**
