### PR TITLE
KillAura Improvements

### PR DESCRIPTION
**Pull request by RickyTheRacc**
- Can now sync with TPS
- Can pause when the server is lagging
- Uses hitboxes in range calcs
- Auto shield breaker (so epic)
- Remove settings that are only useful on smps (cope)

Also adds new TimerUtil object for measuring passed MS and ticks, will be also used in CA etc in later PRs :muscle:

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
Give an example

**Comment by I-Got-You-Dead** [comment]
Only on look, hit chance and so on

**Comment by I-Got-You-Dead** [comment]
An example of the use case would be protecting a baritone bot or afk mob farming

**Comment by RickyTheRacc** [comment]
Neither of those are flagged by anticheat lmfao, rotate is the same thing as only on look except it doesn't require making you look "legit", hit chance has never been checked against, and "so on" means you ran out of examples

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by I-Got-You-Dead** [comment]
Maybe not on a strict ac

**Comment by I-Got-You-Dead** [comment]
Although I agreed random tp should be removed, that’s retarded af

**Comment by RickyTheRacc** [comment]
*On any anticheat

I've tested this stuff out on every 1.19 server I've got knowledge of, and it works everywhere I could find lmao. There has never to my knowledge been a check for how successful your hits are on an anarchy server, and only on look is just worse rotations

**Comment by I-Got-You-Dead** [comment]
> *On any anticheat
> 
> I've tested this stuff out on every 1.19 server I've got knowledge of, and it works everywhere I could find lmao. There has never to my knowledge been a check for how successful your hits are on an anarchy server, and only on look is just worse rotations

I mean igs, if this gets merged I might just make my own ka or something then

**Comment by RickyTheRacc** [comment]
Mmmmm some oddness rn gimme asec

**Pull request merged**
