### PR TITLE
fixed autoeat not working when using shield/offhand items

### PR DESCRIPTION
**Pull request by Seaturtle111501**
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

made it so if you are holding up shield, autoeat triggers after you drop it. fixed the bug that made your shield stay up instead of eating

## Related issues

#4203 

# How Has This Been Tested?

request video if needed

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by idk73248** [comment]
huh

**Comment by moritz-t-w** [comment]
@Seaturtle111501 why did you close this?

**Comment by Seaturtle111501** [comment]
There should be a fix? Is it not working?

**Comment by moritz-t-w** [comment]
I haven't tested it, I just saw that you closed you pr without merging

**Comment by Seaturtle111501** [comment]
I don't remember closing it. I believe I sent a pull request and it got merged but apparently it hasn't. Sorry I am not good with github

**Comment by Seaturtle111501** [comment]
If so what should I do?

**Comment by moritz-t-w** [comment]
Pretty sure you can reopen it bu you might not cause you deleted your repo. In that case just make a new one. If you are allowed you can then merge it.

**Comment by moritz-t-w** [comment]
image

**Comment by moritz-t-w** [comment]
image
Ah I see. Looks like you're gonna have to make a new one

**Comment by Seaturtle111501** [comment]
Would you like me to make a new pull request?

**Comment by moritz-t-w** [comment]
Yeah. If you want the code and have the github cli installed, just do `gh pr checkout 4219`

**Comment by moritz-t-w** [comment]
just to copy paste tho, I don't think you can recreate your fork from that.

**Comment by Seaturtle111501** [comment]
that should fix it hopefully

**Pull request closed without merging**
