### PR TITLE
new features for waypoints

### PR DESCRIPTION
**Pull request by HacktheTime**
## Type of change

- [x] New feature
- [x] some minor bug fixes in the same area

## Description

Added optional parameters to the .waypoint add command and some special waypoint types which offer autodeletion or auto-hiding if wanted. The default for those is off. All changes have to be activated actively.
Syntax: .waypoint add [name] <x> <y> <z> <Dimension> <Type>
Dimension is written out or the first character. Type is like everything but name optional and offers to automatically hide or remove the waypoint when coming close. If a parameter isn't given the original command is performed. If not specified the current locations are expected like previously

## Related issues

none

# How Has This Been Tested?
A lot of trial and error during testing, rereading code. Using features for a bit as testing etc.
Screenshot_20230417_220446
Screenshot_20230417_220538
Screenshot_20230417_220929
Screenshot_20230417_220944

# Checklist:

- [x] My code follows the style guidelines of this project. (First time ever so better look through it as well but im confident.)
- [x] I have added comments to my code in more complex areas. (There are no complex areas at all)
- [x] I have tested the code in both development and production environments.

[Waypoint.zip](https://github.com/MeteorDevelopment/meteor-client/files/11255652/Waypoint.zip) (modified code cause idk intelij with git)

### CODE REVIEW

**Comment by arlomcwalter** [comment]
what the actual fuck

**Comment by HacktheTime** [comment]
> what the actual fuck

what do you mean?

**Comment by Wide-Cat** [comment]
There is merit in your ideas, and we do appreciate the attempt. However, we can't really merge this as is because the actual changes you made aren't in the pr itself, just linked in a file. In order to properly open a pr, you need to fork this repository, then open your fork in intellij, make your changes there, commit the changes to your fork, and then open a pull request from that. I would strongly recommend looking up a guide for this on youtube or something. If you can open a proper pr we'll be able to review it more properly.

Also, a lot of your code doesn't follow the style with the rest of meteor's codebase. I'd suggest looking through some of the other classes and such to see how things are usually done, and styling it as such.

**Comment by HacktheTime** [comment]
> There is merit in your ideas, and we do appreciate the attempt. However, we can't really merge this as is because the actual changes you made aren't in the pr itself, just linked in a file. In order to properly open a pr, you need to fork this repository, then open your fork in intellij, make your changes there, commit the changes to your fork, and then open a pull request from that. I would strongly recommend looking up a guide for this on youtube or something. If you can open a proper pr we'll be able to review it more properly.
> 
> Also, a lot of your code doesn't follow the style with the rest of meteor's codebase. I'd suggest looking through some of the other classes and such to see how things are usually done, and styling it as such.

I let Chat-GPT run through the code again to see if I broke any of the conventions cause I try to implement them in the beginning anyway.  It says there were no breaks of them. I hope it didn't mess it up and it is fine.  You mentioned a lot of git-related stuff which I am DEFINITELY trying to make better, but you furthermore mentioned problems with my coding style not being similar to the one of Meteor. I personally have no idea how I could try to fix this because a) I do not know how to filter out the meteor conventions of the code and b) I have no great experience in Minecraft Coding as I said earlier already. This causes the problem that I have no idea what a lot of the stuff in most Classes is about because there is a high usage of custom usages I never heard about. Basically, I am missing a lot of vocabulary to even understand those classes.

**Pull request closed without merging**
