### PR TITLE
Notebot Enhancements And Fixes

### PR DESCRIPTION
**Pull request by EpicPlayerA10**
### Features:
- Use all instruments corresponding to the song, not only 24 random instruments (https://www.youtube.com/watch?v=WJXuNnLWF5Y)
- Note Map where you can map notes to those to be played
- Auto Play Toggle
- Auto Rotate Toggle
- There are now two Notebot Modes: `AnyInstrument`, `ExactInstrument`
- Round Out Of Range Toggle
### Fixes:
- Fixed bug where song was not playing at the start

Ps. Tested on LiveOverflow's minecraft server (if someone knows this youtuber)

### CODE REVIEW

**Comment by Wide-Cat** [comment]
From the looks of it, the 'Any' mode is essentially how the old notebot worked, and the 'One To One' mode actually makes sure it uses the right instruments, requiring building something like in the linked video? If so, I would change the names of those to be more descriptive, or maybe add some additional clarification in the setting description

**Comment by I-Got-You-Dead** [comment]
Can someone merge this 💀

**Review by I-Got-You-Dead — APPROVED** [review]

**Comment by InstallHappiness** [comment]
Amazing! Should 100% be merged :D

**Comment by MineGame159** [comment]
Sorry for the late response but I have a few things:
1. When I tried to use Exact mode while I didn't have all the required instruments it crashed after tuning the noteblocks.
image
2. Could you format the names in the Note Map category from HARP to Harp.
3. Could you make the missing note message a bit nicer for example: `Missing note: <note> (<block>), <level>`.

Otherwise good job.

**Comment by MineGame159** [comment]
Crashes on load.

**Comment by EpicPlayerA10** [comment]
I know. Fixing it rn

**Comment by EpicPlayerA10** [comment]
Okay, this commit works

**Pull request merged**
