### PR TITLE
1.21.2/.3 update

### PR DESCRIPTION
**Pull request by Big-Iron-Cheems**
## Type of change

- [ ] Bug fix
- [x] New feature

## Description

1.21.2/.3 update

## Related issues

None.

# How Has This Been Tested?

Not tested yet.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [ ] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by vanvac** [comment]
hope 1.21.3 version realeses soon 👍 geter work by ppl much smarter than me

**Comment by zen643** [comment]
will it release before 1.21.4

**Comment by zen643** [comment]
> will it release before 1.21.4

and how to download other version

**Comment by BrownNPC** [comment]
update?

**Comment by vanvac** [comment]
any eta?  or no promises yet

**Comment by vanvac** [comment]
🤞

**Pull request merged**
