### PR TITLE
Update PlayerListHudMixin.java

### PR DESCRIPTION
**Pull request by P529**
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

Fixes compatiblity with future

Would love to push this of 0.5.4

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by RacoonDog** [comment]
it would be better to have it work alongside future instead of disabling the mixin

**Comment by P529** [comment]
> it would be better to have it work alongside future instead of disabling the mixin

I get that but Future is modifying the same constant and my approach was that it wouldn't really matter if one was at least left with the option from future, I can look for another way to solve this.

**Comment by 0xTas** [comment]
> it would be better to have it work alongside future instead of disabling the mixin

This is accomplished by [#4454](https://github.com/MeteorDevelopment/meteor-client/pull/4454)

**Comment by Wide-Cat** [comment]
3145c37fa1473fa5877a665057dc6d99eee0395c

**Pull request closed without merging**
