### PR TITLE
Added onlyOnWeapon option to Hitboxes module

### LINKED ISSUE #2456: [Suggestion] item or slot specific hitbox
### Describe the feature

I like to use hitboxes a lot in my personal world or smps as it just makes fighting mobs less boring and lets you focus on building, but i don't really use them much at all for anything else, would be nice if you had an option for hitboxes to expand only while having some hand picked items picked or being on a specific slot

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### PR DESCRIPTION
**Pull request by DesiCow**
Only modifies hitbox when holding a weapon in hand. Closes #2456

### CODE REVIEW

**Comment by arlomcwalter** [comment]
should add bows too

**Comment by Wide-Cat** [comment]
does that actually work? surely arrows are handled by the server

**Comment by arlomcwalter** [comment]
maybe idk, worth a test

**Comment by DesiCow** [comment]
Tested: All the projectiles do NOT work with client-side enlarged hitboxes.

**Pull request merged**
