### PR TITLE
Improve Potions Hud

### PR DESCRIPTION
**Pull request by RickyTheRacc**
Add a whitelist/blacklist setting, sorting by length, an option to use the normal hud colors, and a choice between normal numbers or roman numerals for effect strength

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
I'll take a look, sure lol

**Comment by seasnale** [comment]
LOL

**Comment by RickyTheRacc** [comment]
(He has no issues open)

**Comment by DesiCow** [comment]
> (He has no issues open)

image

**Comment by seasnale** [comment]
:OoO:

**Pull request closed without merging**
