### PR TITLE
Added Utilities Useful for LiverOverflow's Minecraft Server

### PR DESCRIPTION
**Pull request by AtomicGamer9523**
Added RoboWalk

### CODE REVIEW

**Comment by seasnale** [comment]
this is an extremely niche module
also the code is really bad and it's pretty evident that you didn't really read other meteor code because there is so much redundant code there

**Comment by TaxEvasiqn** [comment]
isnt this a direct paste from coffee

**Comment by FurnyGo** [comment]
3000🎉

**Comment by AtomicGamer9523** [comment]
> isnt this a direct paste from coffee

https://github.com/Saturn5Vfive/robowalk

**Pull request closed without merging**
