### PR TITLE
Do things

### LINKED ISSUE #2383: [Bug] Crash at startup
### Describe the bug

[crash-2022-06-14_13.28.10-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8897189/crash-2022-06-14_13.28.10-client.txt)

### Steps to reproduce

```bash
Launch the client
```

### Meteor Version

dev 1496

### Minecraft Version

19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

### PR DESCRIPTION
**Pull request by RacoonDog**
Fix #2383 
Adds the MiddleClickExtra part of #2382 
Update BetterChat for 1.19 compat + performance stuff

### CODE REVIEW

**Comment by RacoonDog** [comment]
Ignore commits 1 and 3, they just github being github bc the fork i used is the same as my earlier pr

**Comment by RacoonDog** [comment]
`meteordevelopment.meteorclient.systems.proxies.Proxies` has a regex pattern that starts with `^` and ends with `$`, this is redundant as it's matcher uses `Matcher.matches()` which tests against the whole string by default.

`meteordevelopment.meteorclient.utils.player.ChatUtils` stores custom prefixes as a list of pairs containing a string and the prefix, where when used it loops through each pair testing the package name against the pair's string.
This can easily be replaced with a `HashMap` where the key would be the string (package name) and value the prefix.
This would improve performance as looping through a list is O(n) while searching in a hashmap is O(1).
Only *downside* would be duplicate keys would no longer be accepted, but the code for the custom prefixes stops at the first match, so that is irrelevant.

**Comment by MineGame159** [comment]
For the ChatUtils thing it uses `startsWith` and doesn't just check for equality.

**Comment by RacoonDog** [comment]
gonna clean this up in another pr

**Pull request closed without merging**
