### PR TITLE
Fix MineGame159

### PR DESCRIPTION
**Pull request by RickyTheRacc**
Cope seethe mald

### CODE REVIEW

**Comment by arlomcwalter** [comment]
this is such a stupid way to do it

**Comment by RickyTheRacc** [comment]
Well the current one doesn't work at all, so it's an objective improvement :/

**Comment by Declipsonator** [comment]
Wasn't DeathMessageS2CPacket not reliable when looking for alternative ways to see if a player died

**Comment by Declipsonator** [comment]
I thought that came up around notifier

**Comment by RickyTheRacc** [comment]
I mean I put the same thing in rickyware for a toggle on death setting and it hasn't failed once so far

**Comment by arlomcwalter** [comment]
> I mean, the current way just doesn't work at all, so this is objectively an improvement

that doesn't make it good

**Comment by RickyTheRacc** [comment]
> that doesn't make it good

No, but it makes it better

**Comment by SIMULATAN** [comment]
>Build failed

**Pull request closed without merging**
