### PR TITLE
Added InfinityMiner HUD and Module

### PR DESCRIPTION
**Pull request by Inclemental-55**
Hi I added a module and an HUD to go along with it called InfinityMiner. This allows indefinite mining, primarily in the nether, provided one has the mending enchantment. The user specifies the target block, and then the block they wish to repair off of. 

For instance one might select ancient_debris and quartz. Via Fabritone, ancient_debris will be mined until a desired durability threshold is reached, at which point it will switch to quartz to repair the pickaxe.

 It also includes an optional setting which will path-find back to where they started once their inventory is full. If their pickaxe reaches the durability threshold on the way home, it will divert to repair it, and then continue on its way home.

### CODE REVIEW

**Comment by notseanyay** [comment]
based

**Comment by MineGame159** [comment]
Good job

**Comment by Inclemental-55** [comment]
Thank you! If there are any issues let me know, happy to keep it up to date. Will be adding auto-skulker filling next I hope.

**Comment by MineGame159** [comment]
Auto skulker filling?

**Comment by squidoodly** [comment]
When you inventory gets full it puts the stuff you are mining into shulkers for you.

**Comment by Inclemental-55** [comment]
Exactly, would be an optional setting. But would extend the mining duration almost infinitely.

**Comment by squidoodly** [comment]
I had the same idea a while ago but I was too lazy to figure it out. lol

Best of luck. I don't think it will be too hard.

**Comment by MineGame159** [comment]
Ohhh, ok good luck

**Comment by Inclemental-55** [comment]
Thank you! Also you guys have done an amazing job with this client. Thank you for letting me contribute.

**Comment by linustouchtips** [comment]
chad commit

**Pull request merged**
