### PR TITLE
Autoreconnect and velocity fix

### PR DESCRIPTION
**Pull request by Clashbestie**
Fixes [AutoReconnect and events](https://github.com/MeteorDevelopment/meteor-client/issues/42#issue-759922788) and [Knockback strange](https://github.com/MeteorDevelopment/meteor-client/issues/142#issue-785459139).

By using mixins to display the custom DisconnectScreen and not the OpenScreenEvent witch return null as Screen when opening most of the Screens, and adding adding a check to the EntityMixin as explained in the second link.

### CODE REVIEW

**Comment by MineGame159** [comment]
Can you remove the INSTANCE field on AutoReconnect and use ModuleManager instead, if you dont want to get it every tick then you can cachce it to a field.

**Comment by Clashbestie** [comment]
> 
> 
> Can you remove the INSTANCE field on AutoReconnect and use ModuleManager instead, if you dont want to get it every tick then you can cachce it to a field.

like that?

**Comment by MineGame159** [comment]
No :sob: using strings is unefficient (only used for saving) and in code you can do it like .get(AutoReconnect.class)

**Comment by MineGame159** [comment]
Also there is a helper ModuleManager.INSTANCE.isAction(AutoReconnect.class) method

**Comment by MineGame159** [comment]
@Clashbestie do you not test your changes? The build failes.

**Comment by MineGame159** [comment]
Hello? @Clashbestie

**Pull request merged**
