### PR TITLE
Added Notebot

### PR DESCRIPTION
**Pull request by C10udburst**
Some examples:
[All Star.txt](https://github.com/MeteorDevelopment/meteor-client/files/6220058/All.Star.txt)
[Still Alive.txt](https://github.com/MeteorDevelopment/meteor-client/files/6220059/Still.Alive.txt)
[Blue.txt](https://github.com/MeteorDevelopment/meteor-client/files/6220062/Blue.txt)
[Fur Elise.txt](https://github.com/MeteorDevelopment/meteor-client/files/6220064/Fur.Elise.txt)

It loads all *.txt files from `.minecraft/meteor-client/notebot/`

It uses format similar to BleachHack for example.
`<tick>:<note>`

### CODE REVIEW

**Comment by MineGame159** [comment]
In future when doing gui stuff you can just do it like this:
```java
WButton btn = add(new WTable()).getWidget();
```

**Comment by C10udburst** [comment]
so should i change it?

**Comment by MineGame159** [comment]
Sure if you want

**Comment by MineGame159** [comment]
Im rewriting the GUI anyways so

**Comment by C10udburst** [comment]
i can make sth like `.notebot load [sth]` or `.noteboat preview [sth]` i guess

**Comment by MineGame159** [comment]
Yeah ig commands could be useful

**Comment by MineGame159** [comment]
👍 Im gonna try it a bit later today

**Comment by MineGame159** [comment]
quite a bit of issues with notebot:
1.) the gui is just completely broken
2.) preview doesnt work
3.) when i try to play a song it tries to tune the noteblocks, places a few but then starts spamming "could not tune noteblock, stopping" and even the one time it actually stopped and didnt spam it still tried to rotate the player (saw in f5)

i couldnt test anything other because it just doesnt work

**Comment by StormyBytes** [comment]
Why not use .nbs format? (note block studio)

**Comment by MineGame159** [comment]
Yeah nbs support would probably be great.

**Comment by C10udburst** [comment]
> Why not use .nbs format? (note block studio)
Because *.nbs is harder to implement :)

**Comment by MineGame159** [comment]
Actually didnt test recording

**Comment by C10udburst** [comment]
Also I would suggest creating a repository with songs in the `MeteorDevelopment` organization. There could be a link to it inside the module

**Comment by MineGame159** [comment]
Dont ever do this again. Adding 2 modules in 1 pr is bad in itself, not speaking of adding a module to already open pr that didnt have it.

**Comment by MineGame159** [comment]
Branches  exist for a reason

**Comment by C10udburst** [comment]
sorry. should i move it?

**Comment by MineGame159** [comment]
1. Why does it sometimes tune the noteblocks wayyy more than whats needed? Like lets say theres 20 total notes (just a random number) and sometimes it loops those 20 notes like 3 times to get the final note.
2. Tuning already placed noteblocks is scuffed. When its playing from already placed noteblocks the notes it plays are different than when it is placing new noteblocks and do not sound at all like the original song.

**Comment by MineGame159** [comment]
Can you please test your code before committing? Why cant you spend longer time on one feature and make it polish instead of committing 20 times.

**Comment by C10udburst** [comment]
> 1. Why does it sometimes tune the noteblocks wayyy more than whats needed?

Didn't notice this issue, but maybe adding a delay will fix this

> 2\. Tuning already placed noteblocks is scuffed. When its playing from already placed noteblocks the notes it plays are different than when it is placing new noteblocks and do not sound at all like the original song.

That's because `BlockUtils` didn't consider a noteblock in the `isClickable` function.

> Can you please test your code before committing?

I address one thing at a time, i'll push bigger commits now ig. Can't you just merge squash anyway?

**Comment by MineGame159** [comment]
Its not that im concerned about git log. Ofc i will squash but to me you make thinks as fast as possible not looking at how polished it is.

**Comment by MineGame159** [comment]
Ok now actually a few last things:
1. Stopping the song should clear the list of block it renders (same goes for clicking play when a song is already playing)
2. You cant stop it while its tuning noteblocks
3. Can you make it load the bleachhack's format too? I assume your python convertor just discards all notes that dont use the default instrument so you could do the same when loading the song.

Apart from those it seems to be working fine 👍

**Comment by C10udburst** [comment]
> 1. Stopping the song should clear the list of blocks it renders. (same goes for clicking play when a song is already playing)

The list of blocks it renders it directly tied to the loaded song. if it will get cleared, replaying songs without loading the song again wouldn't be possible. if you don't care about the ability to replay songs (without retuning or replacing noteblocks), i can clear it, but otherwise, you can just toggle the module off.

> 2\. You cant stop it while its tuning noteblocks.

Yes you can, just disable the module

> 3\. Can you make it load the bleachhack's format too? I assume your python convertor just discards all notes that dont use the default instrument so you could do the same when loading the song.

ok ill just make it discard if it's a drum sound maybe

**Pull request closed without merging**
