### PR TITLE
Chinese font rendering fix

### PR DESCRIPTION
**Pull request by Nippaku-Zanmu**
我修改了这个文件使CostumFont可以正常渲染中文(包括其他语言)字体
这对正常英文字体渲染性能没有影响
(我不会使用OpenGL,其他字体渲染的性能问题我无法解决 但是这些更改可以使他正常渲染其他语言的字体)

The following is a machine translation of my words

I modified this file so that CostumFont renders Chinese (including other languages) fonts normally
This has no effect on normal English font rendering performance
(I won't use OpenGL, performance issues with other font rendering I can't fix, but these changes make him render fonts in other languages normally)
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

A summary of the changes along with the reasoning behind the changes.

## Related issues

Mention any issues that this pr relates to.

# How Has This Been Tested?

Videos or screenshots of the changes if applicable.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by Nippaku-Zanmu** [comment]
需要使用中文字体,否则会导致游戏崩溃 这意味着需要修改MeteorClient的默认字体 (默认使用的Comfortaa字体不包括中文 我在测试时使用了 HP Simplified Hans字体,没有第一时间发现此问题)

You need to use Chinese fonts, otherwise it will cause the game to crash This means that the default font of MeteorClient needs to be modified (the default Comfortaa font does not include Chinese I used HP Simplified Hans font during testing and did not find this problem in the first place)

**Comment by Nippaku-Zanmu** [comment]
需要使用带有中文的字体,否则无法正常渲染(可能导致游戏崩溃) 这意味着需要修改MeteorClient的默认字体 (默认使用的Comfortaa字体没有中文 我在测试时使用了 HP Simplified Hans字体,没有第一时间发现此问题)

You need to use a font with Chinese, otherwise it will not render properly (may cause the game to crash) This means that the default font of MeteorClient needs to be modified (the default Comfortaa font used does not have Chinese I used HP Simplified Hans font during testing and did not find this problem at the first time)

**Comment by Nippaku-Zanmu** [comment]
> The comments inside of meteor's codebase should all be in English. Everyone who contributes to this project speaks English

Ok, can I use machine translation?

**Comment by Wide-Cat** [comment]
Machine translation should be fine

**Comment by Nippaku-Zanmu** [comment]
> Machine translation should be fine

That's good

**Comment by Wide-Cat** [comment]
We will implement a more comprehensive fix to allow rendering more unicode characters

**Comment by E0x72-21** [comment]
> We will implement a more comprehensive fix to allow rendering more unicode characters

It's been over a year since this PR was closed. I would like to know what is the current progress on this fix. :)

**Comment by Nippaku-Zanmu** [comment]
> > We will implement a more comprehensive fix to allow rendering more unicode characters
> 
> It's been over a year since this PR was closed. I would like to know about the current progress on this fix. :)

you can try this plugin https://github.com/Nippaku-Zanmu/meteor-translation-addon

**Pull request closed without merging**
