### PR TITLE
fix shulker peek

### PR DESCRIPTION
**Pull request by RacoonDog**
## Type of change

- [X] Bug fix
- [ ] New feature

## Description

also performance improvements

# How Has This Been Tested?

the J

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by GreemDev** [comment]
the j is back

**Comment by Wide-Cat** [comment]
Doesnt really look right. Ender pearl x144 is 9 stacks, plus 139 more?

**Review by Wide-Cat — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by Wide-Cat** [comment]
i think this has been fixed as of ac962675cb2672d134fda1d51aee8a11c024de39

**Pull request closed without merging**
