### PR TITLE
add an option in inv tweaks to change the entity model in your inv

### PR DESCRIPTION
**Pull request by Wide-Cat**
@MineGame159 accept my pr or you're a coper for all eternity

### CODE REVIEW

**Comment by MineGame159** [comment]
I really don't see why this should be in Meteor. If you want you can make a PR with just the entity setting and add it to some addon.

**Comment by Wide-Cat** [comment]
😭

**Comment by RickyTheRacc** [comment]
Enormous cope from mimgam

**Comment by necrophili** [comment]
Can #24946bd be pulled at least 😭

**Pull request closed without merging**
