### PR TITLE
Add More Blink Options

### PR DESCRIPTION
**Pull request by Theboiboi8**
Adds options for Trail and Fake Player to the "Blink" module.
Example

### CODE REVIEW

**Comment by arlomcwalter** [comment]
all of the settings can go into sgGeneral

**Comment by MineGame159** [comment]
I don't see the point why Blink should completely replicate Breadcrumbs. You can bind both to the same key to toggle them together.

**Comment by Theboiboi8** [comment]
> 

ye but fakeplayer
also convenience

**Comment by Theboiboi8** [comment]
and I mean you might be using breadcrumbs for smthn else and it might interfere if you just bind the same key for breadcrumbs

**Comment by Theboiboi8** [comment]
also this way it's more accessible

**Comment by Vitalasy** [comment]
based pr

**Pull request closed without merging**
