### PR TITLE
Added FishHack

### PR DESCRIPTION
**Pull request by AstroOrbis**
Why not?

### CODE REVIEW

**Comment by AstroOrbis** [comment]
ignore the amount of commits kekw

**Comment by seasnail8169** [comment]
Also all of these changes are just not what this module should be. The module should give you more control in water not just stop you from moving. Also why are you trying to add an action?

**Comment by AstroOrbis** [comment]
> Do you not work on an IDE?

I do, its just that none of my imports were working, so I had to use github actions to build it whenever I do a change. MineGame159 helped me get them to work, so I finally got to do that.



> Also all of these changes are just not what this module should be. The module should give you more control in water not just stop you from moving.

How would I do that? It takes the X and Z velocity of the player, and only changes the Y.

**Comment by seasnail8169** [comment]
https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/hacks/FishHack.java

**Comment by seasnail8169** [comment]
myes

**Comment by AstroOrbis** [comment]
> myes

I used that as a base... I got help from Jesus.java and Flight.java for the rest :3

**Comment by AstroOrbis** [comment]
wait i forgot to remove the copyright notice from wurst

**Comment by seasnail8169** [comment]
bruh.

**Comment by AstroOrbis** [comment]
?

**Comment by AstroOrbis** [comment]
*confused sounds*

**Comment by AstroOrbis** [comment]
Allright... guess ima start from scratch then :p

**Comment by AstroOrbis** [comment]
I mean this *does* add #363

**Comment by seasnail8169** [comment]
AstroOrbis: King of the Pasters.

**Comment by AstroOrbis** [comment]
[isnt that all of us?](https://stackoverflow.com/)

**Comment by MineGame159** [comment]
Also why not make it better than just what they wanted? Like for example remove the swimming movement completely and not just gravity. `dont ask me how, idk`

**Comment by AstroOrbis** [comment]
hmm... ill get researchin

also thanks for the gradle reload tip :)

**Pull request closed without merging**
