### PR TITLE
Made window title customizable

### PR DESCRIPTION
**Pull request by Lerbiq**
Implements [#536](https://github.com/MeteorDevelopment/meteor-client/issues/536)

### CODE REVIEW

**Comment by seasnail8169** [comment]
fuck you

**Comment by MineGame159** [comment]
:troll:

**Comment by seasnail8169** [comment]
if you merge this im quitting

**Comment by MineGame159** [comment]
Why are there `setTitleText` and `getTitleText` when the field is public? Can't you just use the field directly?

**Comment by Lerbiq** [comment]
True that

**Pull request merged**
