### PR TITLE
.give and .damage tweak

### PR DESCRIPTION
**Pull request by C10udburst**

### CODE REVIEW

**Comment by MineGame159** [comment]
image
What the fuck is this formatting

**Comment by C10udburst** [comment]
vs code is retarded

**Comment by MineGame159** [comment]
Use intellij :skull:

**Comment by seasnail8169** [comment]
1. use intellij
2. what the fuck is the point of .give???

**Comment by C10udburst** [comment]
allows creative mode players to get items not found in creative menu

**Comment by seasnail8169** [comment]
idk it seems kinda useless to me

**Comment by seasnail8169** [comment]
you can already do that with creative hotbars

**Comment by C10udburst** [comment]
most other clients have this feature but idk

**Comment by seasnail8169** [comment]
ive never seen it in any client, sounds like the sort of thing wurst would have or some shit

**Comment by C10udburst** [comment]
So should I remove it and just leave the .damage tweak?

**Comment by seasnail8169** [comment]
can you just remove it so we can merge the other one, .give is useless

**Comment by seasnail8169** [comment]
yeah
also please join the discord, talking on here is aids

**Comment by seasnail8169** [comment]
also please get intellij lmfao

**Pull request merged**
