### PR TITLE
Middle Click Extra -> Keybind Action

### PR DESCRIPTION
**Pull request by RickyTheRacc**
No longer requires the item to be in your hotbar 
Merged Middle Click Friend
Renamed to "Bind Click Extra"
Made the action key configurable

### CODE REVIEW

**Comment by seasnale** [comment]
the name is retarded, makes no sense

**Comment by seasnale** [comment]
also remove those comments

**Comment by RickyTheRacc** [comment]
I couldn't think of anything better ig, if you have ideas

Also rip

**Comment by seasnale** [comment]
also i think middle click friend should be its own module

**Comment by RickyTheRacc** [comment]
I would disagree, I mean if you're using both at the same time then like 
Why?

**Comment by RickyTheRacc** [comment]
As for the name Lemme think then ig

**Pull request closed without merging**
