### PR TITLE
1.21 update

### PR DESCRIPTION
**Pull request by Big-Iron-Cheems**
## Type of change

- [ ] Bug fix
- [X] New feature

## Description

1.21 update

## Related issues

None.

# How Has This Been Tested?

Note
- Broken: PlayerArmorSlotMixin, BufferBuilderAccessor, BlockListSettingScreen, possibly stuff close to Identifier
- Might want to wait for VFP to update?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [ ] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by crazymoose77756** [comment]
MeshVertexConsumerProvider

**Comment by Nippaku-Zanmu** [comment]
The Clip feature in Camera Tweaks causes the game to crash

java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap')
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValueF(CallbackInfoReturnable.java:120) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.minecraft.class_4184.method_19318(class_4184.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_4184.method_19321(class_4184.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1052) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

**Comment by Wide-Cat** [comment]
😩

**Comment by OfflinePing** [comment]
I checked it out and it built fine and also works quite stable in game for me. Although there are missing Modules like Infinity Mine is that correct?

**Comment by Big-Iron-Cheems** [comment]
> I checked it out and it built fine and also works quite stable in game for me. Although there are missing Modules like Infinity Mine is that correct?

image
Some modules only appear if you have Baritone in your mods folder as they can't be used without it.

**Comment by Matti074567** [comment]
how i become i 1.21 yet

**Pull request merged**
