### PR TITLE
Baritone smart sprint

### PR DESCRIPTION
**Pull request by nothub**
This adds a setting to automatically enable and disable Baritones sprint based on food saturation.

### CODE REVIEW

**Comment by nothub** [comment]
> We are not developers of Baritone.

?

**Comment by MineGame159** [comment]
This should be suggested to Baritone, not us.

**Comment by MineGame159** [comment]
Jesus christ im blind. Sorry about that. Either way I don't see how this is useful, surely it is better to make it eat, aka Auto Eat.

**Comment by nothub** [comment]
I use it for the situation where the players food items are used up to automatically stop sprinting.

**Comment by nothub** [comment]
just for reference, addon lives here now https://github.com/nothub/meteor-baritone-tweaks

**Pull request closed without merging**
