### PR TITLE
Invisible filter for KA

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**

### CODE REVIEW

**Comment by arlomcwalter** [comment]
why

**Comment by ThebestkillerTBK** [comment]
#974

**Comment by arlomcwalter** [comment]
i mean why would this be useful not why did you do it

**Comment by arlomcwalter** [comment]
seems like its just for cheating

**Comment by ThebestkillerTBK** [comment]
nvm the filter is just here

**Comment by arlomcwalter** [comment]
what?

**Pull request closed without merging**
