### PR TITLE
Notebot Midi decoder

### PR DESCRIPTION
**Pull request by Fiz-Victor**
## Type of change

- [ ] Bug fix
- [X] New feature

## Description

Unknown decoder fallback to TXT mode, added Midi Decoder

# How Has This Been Tested?

Grab a midi to the notebot folder and play

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by I-Got-You-Dead2** [comment]
Bruh

**Comment by I-Got-You-Dead2** [comment]
Honestly fuck you

**Comment by I-Got-You-Dead2** [comment]
IMG_3413

**Comment by Fiz-Victor** [comment]
anyways use note block studio to convert nbs files
dont wanna work on it

**Pull request closed without merging**
