### PR TITLE
Proxy Names

### LINKED ISSUE #513: [SUGGESTION] Option to name saved proxies
**Describe the feature**
As said in the title, adding a box to give a proxy a name.
Could be added in the Optional section, makes it easier to know where you are connecting to.

**Screenshots**
2021-04-15 21_49_11-Minecraft 1 16 5

### PR DESCRIPTION
**Pull request by StormyBytes**
Resolves #513

### CODE REVIEW

**Comment by Wide-Cat** [comment]
👍

**Comment by MineGame159** [comment]
1. Why is name optional
2. Why is the name not shown in multiplayer screen
3. I think the name should go after the checkbox in the GUI

**Comment by StormyBytes** [comment]
Anything else?

**Comment by MineGame159** [comment]
Yes, change Proxy.isValid to check if the name is not empty

**Comment by StormyBytes** [comment]
Done

**Comment by MineGame159** [comment]
There is isEmpty() method on string.

**Pull request merged**
