### PR TITLE
added a seed system and rewrote locate

### LINKED ISSUE #956: [Suggestion] Seed Manager
A database of seeds for each world/server. The value could be set using `.seed` (taken for example from [SeedCracker](https://github.com/KaptainWutax/SeedCracker)) and used in calculations for `.locate` and  in future maybe for slime chunk calculation or OreSim like in #537

### LINKED ISSUE #978: [Suggestion]
add slime chunk esp

### LINKED ISSUE #980: Suggestion for .locate (second mechanic)
**Describe the feature**
.locate command can locate strongholds, mansions, buried treasures etc. based on teasure maps or ender eyes.
I would be grateful if you add second mechanic for .locate command which will work based on world seed.
For example user will type .locate <structure> <seed> and (this utility mod) will locate nearest <structure> by using this seed to generate copy of world.

**Additional info**
I have already seen this feature in the utility mod impact client.

### LINKED ISSUE #1107: [Suggestion] Make .locate work with a given seed
This would be so useful, when searching for structures/biomes (no op permissions needed)

### LINKED ISSUE #1319: [Suggestion]
Module allows you to input the servers seed and automatically sets waypoints based on the structure you've selected and the amount of waypoints.
For example, typing ".structurefinder dungeon 4" would set 4 waypoints named "Dungeon1, Dungeon2, Dungeon3, Dungeon4" based on the distance from the player to the nearest dungeon(s).
This would be useful for finding end portals, desert temples for Egapp hunting on servers without dupes, etc.

command
message after usage
suggestion

### LINKED ISSUE #1369: [Suggestion] Structure Finder
**Describe the feature**
Find Structures based on the seed or coordinates

**Screenshots**
this is a screenshot from Aristois client but not working well
Immagine

**Additional info**
for Stronghold Finder I suggest use the 2 ender eyes calculation and after show up on chat the coords for use #goto

### PR DESCRIPTION
**Pull request by C10udburst**
- Added a seed system
- `.seed` command for viewing and changing seeds for each server
- Moved most of the `.locate` logic to `WorldGenUtils`
- Seeds can be now used to locate structures
- If no seed is present fallback methods will be used as before (including new way of using entities specific for a given feature)

## Issues
Closes #1107 
Closes #980 
Closes #956
Closes #978
Closes #1319
Closes #1369 

Implements base for #537

### CODE REVIEW

**Review by GibsonHF — APPROVED** [review]

**Comment by C10udburst** [comment]
no idea why the build failed, should work properly.

@GibsonHF please review :trollface:

**Comment by GibsonHF** [comment]
My bad lol was fucking with ide and somehow managed to do that

**Comment by RedCarlos26** [comment]
This is awsome it needs to be merged

**Comment by C10udburst** [comment]
@GibsonHF does this look ok? :trollface:

**Comment by maxsupermanhd** [comment]
Works fine for me, no crashes no undefined stuff. Would be also cool to set seed with letters (including spaces) using quotes.

**Comment by RedCarlos26** [comment]
> Works fine for me, no crashes no undefined stuff. Would be also cool to set seed with letters (including spaces) using quotes.

Especially if the map seed has these types of characters

**Comment by C10udburst** [comment]
cope about it

**Comment by RickyTheRacc** [comment]
Why has this not been merged or updated? This is nice asf

**Comment by RedCarlos26** [comment]
True

**Comment by RedCarlos26** [comment]
Why was this closed

**Comment by RedCarlos26** [comment]
Meteor moment 😂

**Comment by arlomcwalter** [comment]
> Meteor moment 😂

badly integrated system moment

**Comment by ooliver1** [comment]
Could have said that as the closing message moment

**Comment by i-am-called-glitchy** [comment]
moment chat moment

**Comment by Sebminecrafter** [comment]
😭 bro this was and has always been needed
cope is wild

**Comment by thatfrozenfrog** [comment]
holy coal

**Pull request closed without merging**
