### PR TITLE
TP-Hit mode for reach module

### PR DESCRIPTION
**Pull request by DesiCow**
As suggested in #1122 , this setting teleports(in multiple segments) the player closer to target, attacks, and returns back to original location.

### CODE REVIEW

**Comment by Wide-Cat** [comment]
you need to do rotation stuff in the Pre tick because of how theyre applied, otherwise it'll be a tick behind, also `new Thread` and `Thread.sleep()` 😩

**Comment by I-Got-You-Dead** [comment]
Bruh no more trolling small children :l

**Comment by I-Got-You-Dead** [comment]
Now we gotta deal with Skript kiddies using tp range 💀

**Comment by I-Got-You-Dead** [comment]
Sadage

**Comment by DesiCow** [comment]
> you need to do rotation stuff in the Pre tick because of how theyre applied, otherwise it'll be a tick behind, also `new Thread` and `Thread.sleep()` 😩
How would you delay sending the packets?

**Comment by DesiCow** [comment]
bad code

**Pull request closed without merging**
