### PR TITLE
fix translation

### PR DESCRIPTION
**Pull request by Enaium**

### CODE REVIEW

**Comment by Wide-Cat** [comment]
whats the difference between the new and previous translation?

**Comment by seasnail8169** [comment]
its probably just mandarin for the word meteor as opposed to the english noun meteor referring to meteor client

**Comment by ThebestkillerTBK** [comment]
打开Meteor输入框 means open Meteor input box, means unclear

**Comment by seasnail8169** [comment]
oh yeah i'm retarded

**Pull request merged**
