### PR TITLE
AutoEZ

### PR DESCRIPTION
**Pull request by OsakiTsukiko**
I saw a similar pull request a while ago and I really liked some features, sadly, the pull req had some issues and was left inactive and then closed, so I thought I would give it a try.

### CODE REVIEW

**Comment by OsakiTsukiko** [comment]
Also, is AutoEZ considered Misc or Combat?

**Comment by RickyTheRacc** [comment]
It's considered horrible and should not be added

**Comment by OsakiTsukiko** [comment]
huh?

**Comment by RacoonDog** [comment]
oh boy another useless chat spamming module

**Comment by RickyTheRacc** [comment]
> huh?

Auto ez is extremely stupid, it's just annoying chatspam and anyone with a brain will just /ignore people using it. If people want to spam ez after every kill they can make a macro but having an entire module dedicated to it is just cringe

**Comment by OsakiTsukiko** [comment]
Not really spamming, just taunting but ok..

**Pull request closed without merging**
