### PR TITLE
Added .run

### PR DESCRIPTION
**Pull request by DAMcraft**
## Type of change

- [ ] Bug fix
- [X] New feature

## Description
Added .run, works like .say, except that it executes meteor, vanilla and baritone commands. Made for usage with starscript, macros and swarm

Should be added after #3428, so that the bug doesn't happen

# How Has This Been Tested?
image

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by I-Got-You-Dead2** [comment]
Why bruh

**Comment by DAMcraft** [comment]
Literally read the description

**Comment by I-Got-You-Dead2** [comment]
But why

**Comment by ManInMyVan** [comment]
Rip conflicts

**Pull request closed without merging**
