### PR TITLE
Added Falling & Non-Solid Filters To Scaffold

### PR DESCRIPTION
**Pull request by TheTerrarian101**
Added Filters for Falling Blocks and Non-Solid Blocks to Scaffold

### CODE REVIEW

**Comment by RoastedCheese** [comment]
I love you.

**Review by StormyBytes — COMMENTED** [review]
Can you move this to a seperate pr?

**Comment by TheTerrarian101** [comment]
> Can you move the killaura changes to a seperate pr?

Alright

**Comment by StormyBytes** [comment]
Why put all of these in 1 pr bruh

**Comment by StormyBytes** [comment]
Use a clearer setting name, instead of `filtFall` use `filterFallingBlocks` or `filterGravityBlocks`

Change `.name("Filter Falling Blocks")` to `.name("filter-falling-blocks")` 
This is crucial because `.setting` command will have problems with names that have spaces in them.

And lastly seperate these changes into seperate PRs

**Pull request closed without merging**
