### PR TITLE
"Fixed" settings.gradle

### PR DESCRIPTION
**Pull request by ed0cinU**
idk why but i had to change this to prevent gradle from not building the project (if it doesnt really matter you can ignore and close this pull request)

### CODE REVIEW

**Comment by ed0cinU** [comment]
it was like Plugin Repositories (could not resolve plugin artifact 'fabric-loom:fabric-loom.gradle.plugin:0.10-SNAPSHOT')

**Comment by arlomcwalter** [comment]
can you try the original settings.gradle configuration and see if it works now

**Comment by ed0cinU** [comment]
ok gimme a few minutes

**Comment by ed0cinU** [comment]
ok wow it didn't happend again, you can close this

**Pull request closed without merging**
