### PR TITLE
Sneak

### PR DESCRIPTION
**Pull request by StormyBytes**
Adds sneak module.

### CODE REVIEW

**Comment by StormyBytes** [comment]
Ignore the "part 1". I thought I still needed to add some more stuff so I named it part 1

**Comment by MineGame159** [comment]
Im pretty sure if you have it active with `packets` set to true and then toggle it to true without toggling the module it will still continue to sneak client side.

**Comment by StormyBytes** [comment]
Should be fixed already.

**Comment by MineGame159** [comment]
Thats not what I meant

**Comment by StormyBytes** [comment]
> Im pretty sure if you have it active with `packets` set to true and then toggle it to true without toggling the module it will still continue to sneak client side.

Sorry, what? I dont understand.

**Comment by StormyBytes** [comment]
Sorry, I didn't understand what you meant, so I assumed there was a bug, went to test it, found a bug (don't know whether this was the thing you meant or not) , and wrote a fix for it.

It seems to be working fine when tested though.

**Comment by mathmakgakpak** [comment]
he meant that other players will see you as sneaking but clientside you won't be crouching and you will be moving with same speed

**Comment by StormyBytes** [comment]
Isn't that the whole purpose of packet sneaking? So that other players see you sneaking but client side you aren't?

**Comment by mathmakgakpak** [comment]
wait did you do it like that? lmfao

**Comment by mathmakgakpak** [comment]
I misunderstood him. Sorry.

**Comment by StormyBytes** [comment]
So... Should this be closed or something? It's been 2 weeks.

**Comment by Declipsonator** [comment]
new forever pr

**Comment by Declipsonator** [comment]
mine lasted a good 2 months before being closed 😭

**Review by AstroOrbis — APPROVED** [review]

**Comment by Wide-Cat** [comment]
Lol, finally :trollface:

**Pull request merged**
