### PR TITLE
Offhand Rewrite

### PR DESCRIPTION
**Pull request by CrytoPal**
## Type of change

- [x] New feature

## Description

Rewrote Offhand which adds Right Click Gapple, Potion Offhand, and Auto Totem in one module

# How Has This Been Tested?

Tested it in AC testing servers + CC (Crystalpvp.cc)

# Videos or screenshots of the changes if applicable.

You can try out the module yourself (I was too lazy to record)

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by CrytoPal** [comment]
Made new branches to make commits look cleaner

**Comment by Wide-Cat** [comment]
- sword gapple has a wrong description
- add an option to have 0 ticks of delay
- if you have a crystal in your offhand and right click to eat a gapple, it will place a crystal on obsidian. Maybe add an option to do something about this, like always holding a gapple when holding a sword
- change it back to just 'offhand', not 'Off Hand'

**Comment by CrytoPal** [comment]
@Wide-Cat 

> * sword gapple has a wrong description
> 
>     * add an option to have 0 ticks of delay
> 
>     * if you have a crystal in your offhand and right click to eat a gapple, it will place a crystal on obsidian. Maybe add an option to do something about this, like always holding a gapple when holding a sword
> 
>     * change it back to just 'offhand', not 'Off Hand'

Fixed the issues stated here

**Comment by Wide-Cat** [comment]
- Sword gapple doesn't seem to work anymore. I was holding a sword and right clicking, but it wasn't transferring a gap to my offhand.
- There seems to be a bug with the delay setting. I couldn't find a method to reproduce it, but if you set the delay to a high value, there are definitely some times where it swaps quicker than it should.
- I'm a little conflicted on the potion setting, it seems like a waste of your offhand slot to me. Maybe remove it from the item enum and instead add an option to hold a strength potion in your offhand if you're holding a sword, you're in a hole and don't have strength already, although I feel like even that could have its flaws and you'd probably just be better off using quiver

**Comment by CrytoPal** [comment]
I

> * Sword gapple doesn't seem to work anymore. I was holding a sword and right clicking, but it wasn't transferring a gap to my offhand.
> 
>     * There seems to be a bug with the delay setting. I couldn't find a method to reproduce it, but if you set the delay to a high value, there are definitely some times where it swaps quicker than it should.
> 
>     * I'm a little conflicted on the potion setting, it seems like a waste of your offhand slot to me. Maybe remove it from the item enum and instead add an option to hold a strength potion in your offhand if you're holding a sword, you're in a hole and don't have strength already, although I feel like even that could have its flaws and you'd probably just be better off using quiver

I Fixed the Sword Gap and added more Potion delays. But I couldn't manage to reproduce the bug with the delay.

**Pull request merged**
