### PR TITLE
Adding gc command to Meteor

### PR DESCRIPTION
**Pull request by albonec**
## Type of change

- [ ] Bug fix
- [x] New feature

## Description

I added .gc command to my fork of meteor because when I used the garbage collector through baritone, it noticeably improved framerate and reduced lag when playing. PLEASE IGNORE LITHIUM, SODIUM FOLDERS. I modified the gradle files for those mods and put them there for easy access when working on my fork.

## Related issues

None really.

# How Has This Been Tested?

I ran the command while playing on 2b2t and had a 100 fps increase, allowing me to escape a quite laggy part of spawn.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by albonec** [comment]
Relevant changes are in GcCommand.java and Commands.java

**Comment by hexadecimal233** [comment]
bettter create an addon

**Comment by GreemDev** [comment]
baritone has a gc command

**Comment by albonec** [comment]
yeah but why should meteor not have one by itself, it is useful ya know

**Comment by MineGame159** [comment]
1. Wouldn't merge this PR even if there were no other issues with it, manually invoking the GC is bad.
2. What the FUCK do you mean ignore the lithium and sodium folders??? You want us to just merge them into meteor?

**Pull request closed without merging**
