### PR TITLE
Settings Code modification and finish a todo

### PR DESCRIPTION
**Pull request by LLKawi**
## Type of change

- [ ] Bug fix
- [X] New feature

## Description

Make all setting constructors are not accessible so the Builder is always called

also finish a todo

## Related issues

N/A

# How Has This Been Tested?

No crash on loading and quitting.

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by arlomcwalter** [comment]
why did you make some of the classes final

**Comment by ThebestkillerTBK** [comment]
> why did you make some of the classes final

Because they should never be inherited

**Comment by RacoonDog** [comment]
i can say i have definitely extended multiple setting classes in the past

**Comment by RacoonDog** [comment]
but yeah seansail private constructor stops you from extending a class even if its not final

**Comment by arlomcwalter** [comment]
> but yeah seansail private constructor stops you from extending a class even if its not final

well ok but i don't think that's necessarily a reason to add final to those classes in this pr

**Comment by arlomcwalter** [comment]
the constructors should all be protected, the ones that aren't are mistakes, not deliberate 

@ThebestkillerTBK could you make all the classes and constructors consistent in this pr?

**Comment by LLKawi** [comment]
closing due to inactivity

**Pull request closed without merging**
