### PR TITLE
Fixed AutoNametag

### PR DESCRIPTION
**Pull request by RedCarlos26**
## Type of change

- [X] Bug fix
- [ ] New feature

## Description

Prevent AutoNametag from straight not working.

## Related issues

None.

# How Has This Been Tested?

Has been tested on both server and singleplayer.

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by RedCarlos26** [comment]
@RacoonDog I resolved the conflict your pr created

**Comment by RedCarlos26** [comment]
@MineGame159 please merge this so we can use AutoNametag again

**Comment by Wide-Cat** [comment]
it doesnt seem to work for renaming entities properly, as it will get hung up on trying to rename one mob even if its already done so

**Comment by RedCarlos26** [comment]
The meteor default one does that, but this fixes it... U less I broke it another way. I'll test some more later and give an update

**Comment by Wide-Cat** [comment]
👁️

**Comment by RedCarlos26** [comment]
Didn't have any time yet unfortunately. Hopefully tomorrow

**Comment by RedCarlos26** [comment]
Works fine for me. If I have the renametag option enabled it will obviously get through and rename a mob that I have already nametagged but this is how it worked before too. What I fixed is the fact that auto nametag wasn't working with this option disabled.

**Comment by RedCarlos26** [comment]
@Wide-Cat should be fine now :)

**Comment by RedCarlos26** [comment]
@Big-Iron-Cheems can you check this for me please? Everything worked fine for me with my recent changes :)

**Pull request closed without merging**
