### PR TITLE
Added bogus-accept resource-packs option to ServerSpoof module

### PR DESCRIPTION
**Pull request by DesiCow**
Automatically sends fake packets to the server that client accepted their resource pack.

### CODE REVIEW

**Comment by ThebestkillerTBK** [comment]
Why use while bro

**Comment by DesiCow** [comment]
> Why use while bro

uhh mc.getNetworkHandler() is sometimes null when joining a server

**Comment by ThebestkillerTBK** [comment]
> > Why use while bro
> 
> uhh mc.getNetworkHandler() is sometimes null while joining a server, that's why I do it in MeteorExecutor service

Have you tested it? The network handler already received the resource packet tho, it cannot be null.

**Comment by DesiCow** [comment]
> > > Why use while bro
> > 
> > 
> > uhh mc.getNetworkHandler() is sometimes null while joining a server, that's why I do it in MeteorExecutor service
> 
> Have you tested it? 
yes

**Pull request closed without merging**
