### PR TITLE
Added chat protection from sending messages with coords in global chat, fixed and improved nbt command

### PR DESCRIPTION
**Pull request by dakone22**
Added chat protection from sending messages and messages with coords in global chat.
By [suggestion](https://discord.com/channels/689197705683140636/689202616441503870/793566248574386247) from `@supakeks#0001` and [suggestion](https://discord.com/channels/689197705683140636/689202616441503870/793556976503619644) from `Chompasaurus513#3571`.
chat_protection

Also fixed `.nbt get` crash with empty nbt data. Added `.nbt copy`. Added chat button for copy in `.nbt get`.
nbt_copy2

### CODE REVIEW

**Comment by MineGame159** [comment]
image
Why is this there?

**Comment by dakone22** [comment]
In order not to forget. Should it be removed?

**Comment by MineGame159** [comment]
image
I dont think its worth it replacing this with that method.

**Comment by dakone22** [comment]
Why? I think it's realy should be replaced than to have `Config.INSTANCE.getPrefix()` + getting name + space + arg

**Comment by MineGame159** [comment]
`Config.INSTANCE.getPrifx() + this.name + " copy"` vs `CommandManager.getCommandString(this.name, "copy")`

You basically just got rid of getting the prefix and replaced it with calling method that requires more characters.

**Comment by MineGame159** [comment]
If you really wanna get fancy then sommething like `CommandManager.get(NBT.class).run("copy")` could work.

**Comment by dakone22** [comment]
> You basically just got rid of getting the prefix and replaced it with calling method that requires more characters.

Yes. And as well you can use muliple args instead adding spaces between them.
```java
CommandManager.getCommandString(

**Comment by MineGame159** [comment]
Imo the run() method would be better.

**Pull request merged**
