### PR TITLE
Custom Yggdrasil Login

### LINKED ISSUE #3143: The Alt manager supports custom Yggdrasil server addresses
### Describe the feature

I want to be able to log in to a third-party YggdrasilAPI server using Alt manager. Log in like a LittleSkin. In addition, I hope I can log in after I have the account name, UUID and session

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
closes #3143
Credit to https://github.com/IAFEnvoy/AccountSwitcher

### CODE REVIEW

**Comment by Wide-Cat** [comment]
who provides custom yggdrasil servers for you to login with? I've never encountered one before

**Comment by ThebestkillerTBK** [comment]
> who provides custom yggdrasil servers for you to login with? I've never encountered one before

see issue #3413

**Comment by 8MiYile** [comment]
> who provides custom yggdrasil servers for you to login with? I've never encountered one before
Custom Login Server
be like Mojang's Auth
But it is not possible to access Hypixel and other such servers that use Microsoft Auth
The third-party login server is designated by the game server and information is not exchanged between different third-party login servers
you can visit [LittleSkin](https://littleskin.cn)
or [authlib-injector](https://github.com/yushijinhun/authlib-injector)

**Comment by 8MiYile** [comment]
WTF？
are you Kidding me？
@MineGame159

**Comment by I-Got-You-Dead** [comment]
:trollface:

**Comment by MineGame159** [comment]
Unless this technique becomes more popular I don't think there is a reason to add it to Meteor. I have not seen a single server use it.

**Comment by 8MiYile** [comment]
in China
this auth is popular

**Comment by Wide-Cat** [comment]
oh, do they block microsoft auth or something

**Comment by 8MiYile** [comment]
@Wide-Cat 
just change the ms auth server to a custom server

**Pull request closed without merging**
