### PR TITLE
Troll Lounge

### PR DESCRIPTION
**Pull request by Declipsonator**
Adds a vertical-range option to scaffold to control how many blocks are placed beneath you. It works with radius, however as expected, it is pretty buggy with radius when you try to place a metric ton of blocks at once ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by Declipsonator** [comment]
I probably fucked smth up tbh

**Comment by Declipsonator** [comment]
💀

**Comment by Declipsonator** [comment]
life is going great

**Comment by RedCarlos26** [comment]
Why is this still not added? Something is broken?

**Comment by seasnail8169** [comment]
:trollface:

**Comment by RedCarlos26** [comment]
So yea what's happening with this lol...

**Comment by mathmakgakpak** [comment]
@seasnail8169 stop trolling

**Comment by Declipsonator** [comment]
> @seasnail8169 stop trolling

:trollface:

**Comment by Declipsonator** [comment]
maybe one day...

**Comment by RedCarlos26** [comment]
It is still not added lmao. Like how XD

**Comment by seasnail8169** [comment]
:trollface:

**Comment by Wide-Cat** [comment]
snale do be trollin

**Comment by seasnail8169** [comment]
It is simply too easy for me.

**Comment by Declipsonator** [comment]
how do I add commits to a pr 🤔

**Comment by seasnail8169** [comment]
just commit to your fork

**Comment by GildedS** [comment]
One month pr starts now

**Comment by Declipsonator** [comment]
:trollface:

**Comment by ekcire06** [comment]
trololoooo

**Comment by Declipsonator** [comment]
https://user-images.githubusercontent.com/80488217/114132172-d986a980-98d1-11eb-9d11-ea5198718c83.png

**Comment by Declipsonator** [comment]
wait what

**Comment by Declipsonator** [comment]
tf

**Comment by Declipsonator** [comment]
image

**Comment by Declipsonator** [comment]
ez

**Comment by Declipsonator** [comment]
celebrating 2 months and 2 days

**Comment by Wide-Cat** [comment]
easily

**Pull request closed without merging**
