### PR TITLE
AutoAnvil update && BugFix

### PR DESCRIPTION
**Pull request by TechAle**
BugFix:
- You were not able to place a block on your enemy (like webs and buttons)

AutoAnvil:
- Added antiStep
- Now it's used a different algorithm for the height of the anvil. Now it's dynamic, it will be placed based on your distance from the enemy (and from the paramers you choosen)

### CODE REVIEW

**Comment by MineGame159** [comment]
Can you resolve conflicts and move `private final ArrayList<Vec3d> antiStepStructure` above constructor? Fields shouldnt be below.

**Comment by MineGame159** [comment]
image
Use BlockPos.Mutable to not create new BlockPos every time, just store one inside a final field and modify it.

**Comment by seasnail8169** [comment]
Or alternatively, in that method, you could use pos.north(), pos.south(), etc which would give you the same thing.

**Comment by TechAle** [comment]
Uh, we i'll be free, i'll try, and i'll resolve everything

**Comment by MineGame159** [comment]
No, dont use .north() etc, they still create a new BlockPos instance.

**Comment by TechAle** [comment]
something is wrong with my commit, why are speed, elytraplus and drawside added? bruh

**Comment by MineGame159** [comment]
Idk but they are still there and have been changed so I cannot merge it without overwriting them.

**Comment by seasnail8169** [comment]
> Idk but they are still there and have been changed so I cannot merge it without overwriting them.

i moved them

**Comment by TechAle** [comment]
So, now this should be fine since snail moved them?

**Pull request merged**
