### PR TITLE
Rounding in UIs

### LINKED ISSUE #544: [Suggestion] Rounded edges in the HUD / ClickGUI
Add an option in the HUD and ClickGUI settings to make all edges rounded. I personally think this looks cooler.

### PR DESCRIPTION
**Pull request by JFronny**
Of course this is optional and disabled by default

Changes after my message in discord:
- The background of windows is drawn 50% into the title bar and not rounded at the top in order to look like it is connected to the window
- Custom rendering for rounded background outlines to facilitate transparency
- Topbar is rounded. If you want i can prevent the upper edges from being rounded, though i kinda like this
- Rounding is a generalized theme property (for HUD support)
- HUD backgrounds are rounded

Closes #544

### CODE REVIEW

**Review by AstroOrbis — APPROVED** [review]

**Review by AstroOrbis — APPROVED** [review]

**Comment by JFronny** [comment]
Build failed because pipeline uses java 8

**Review by AstroOrbis — APPROVED** [review]

**Comment by AstroOrbis** [comment]
@seasnail8169

**Review by AstroOrbis — APPROVED** [review]

**Comment by seasnail8169** [comment]
what

**Comment by AstroOrbis** [comment]
merge it or you're a baka

**Comment by seasnail8169** [comment]
no

**Comment by Cypphi** [comment]
mfw (my face when) still not accepted :trollface:

**Comment by AstroOrbis** [comment]
lmao

**Comment by C10udburst** [comment]
just use [this](https://github.com/JFronny/meteor-client) or [this](https://github.com/C10udburst/meteor-rejects) lol

**Comment by StormyBytes** [comment]
New 2 month pr?

**Comment by AstroOrbis** [comment]
dang

**Comment by Cypphi** [comment]
What's even the reason it's not getting accepted, I tried it and it's very sex. The only issue is that the rounded lines aren't very smooth for some reason...

**Comment by RedCarlos26** [comment]
Yea that's all

**Comment by JFronny** [comment]
Due to the implementation, some aliasing is bound to happen. That is also the reason why I keept the old circle icon for scrollbars: With small circles this effect becomes rather apparent. However, it is the simplest and least convoluted way to implement this into the current codebase and still looks good. (Also the only one I know how to do)

**Comment by Cypphi** [comment]
Ah, interesting, I think it should be accepted and be turned off my default until it's fully done / looks clean because then i'd be a great feature to have as default since it just looks better

**Comment by RedCarlos26** [comment]
Seasnail will never merge it caus he does not like round edges... 😒

**Comment by AstroOrbis** [comment]
or he's just going to leave the git branch straight as a joke
(git trees go brrrrr)

**Comment by seasnail8169** [comment]
or its just not very good
well not bad but not perfect at least

**Comment by JFronny** [comment]
This is as far as I can currently improve this and I don't think it would have any negative impact by being merged as is. If anyone has any idea for improvements after that, they could still open their own PRs. Also IMO it really doesn't look that bad.

**Comment by BobIsMyManager** [comment]
> or its just not very good
> well not bad but not perfect at least

Maybe add as an option instead of replacing if it isn’t already

**Comment by JFronny** [comment]
An option to select by how much everything is rounded is shown and set to 0 by default (= no rounding)

**Comment by Cypphi** [comment]
It's possible to make the curves smooth with OpenGL stuff right

**Comment by RedCarlos26** [comment]
> It's possible to make the curves smooth with OpenGL stuff right

Yea I think so

**Comment by JFronny** [comment]
Already known, however these are things that I am too stupid to fix without large amounts of very bad code

**Comment by AstroOrbis** [comment]
> TYad8FrPud.mp4 
> 
> This prob was a known issue already but the hover effect overrides the rounded edges

Ain’t that sigma

**Comment by Cypphi** [comment]
> > TYad8FrPud.mp4
> > This prob was a known issue already but the hover effect overrides the rounded edges
> 
> Ain’t that sigma

meteor

**Comment by StormyBytes** [comment]
5 month old pr

**Review by C10udburst — APPROVED** [review]

**Comment by Lerbiq** [comment]
The pr makes the game crash with memory allocation error. "corrupted size vs. prev_size" and sometimes this "java: malloc.c:4259: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed."

This happens when you open the accounts screen with the round setting set to 7 and two cracked accounts in the manager after starting the game. 

Opening the click gui before you open the accounts prevents the game from crashing, however it introduces a new issue when you then close the accounts screen, go to main menu and quit the game using the button in the game. The game will crash with this error: "double free or corruption (out)" and won't let meteor save.

Those issues seem to occur only when the round setting is set to 7 only.

**Comment by MineGame159** [comment]
Closing this PR because the GUI is going go get rewritten in the near future and will most probably include rouded corners.

**Comment by Wide-Cat** [comment]
RIP 😔

**Comment by RickyTheRacc** [comment]
RIP? Minegame just confirmed gui rewrite that's sexyyy 😳

**Comment by RedCarlos26** [comment]
8 months later 🤩

**Comment by MineGame159** [comment]
Uhhhh uhhh :eyes:

**Comment by C10udburst** [comment]
🤨

**Comment by i-am-called-glitchy** [comment]
scam

**Pull request closed without merging**
