### PR TITLE
new module and improvment

### PR DESCRIPTION
**Pull request by MaslovKK**
all commits has a comments

### CODE REVIEW

**Comment by Talhoid** [comment]
i think you mean new module not "hack"

**Review by RacoonDog — CHANGES_REQUESTED** [review]
Max jump is active even when Entity Control is not

**Comment by MaslovKK** [comment]
> Max jump is active even when Entity Control is not

ur'e wrong, i'm checked it's now - everything is fine

**Review by katant — CHANGES_REQUESTED** [review]
хуйня переделывай

**Comment by ne-lanskoy** [comment]
а ты знал что твоя мама шлюха?

**Comment by Wide-Cat** [comment]
With ignore border enabled, I can break blocks and such beyond the world border, but can't actually walk through it. Entity control seems to work much the same as before.

**Comment by MaslovKK** [comment]
> With ignore border enabled, I can break blocks and such beyond the world border, but can't actually walk through it. ~Entity control seems to work much the same as before~ I think a desync bug with entity control is fixed, which is epic

U can walk through it, is u play vanilla or spigot?

**Comment by Wide-Cat** [comment]
i was on singleplayer

**Comment by MaslovKK** [comment]
5 months ignoring pr's. Best responsiveness!

**Comment by ThebestkillerTBK** [comment]
thank god

**Pull request closed without merging**
