### PR TITLE
Nuker blacklist

### LINKED ISSUE #2256: [Suggestion]
### Describe the feature

Maybe make the nuker have a block blacklist not only whitelist so you can blacklist blocks you would like to not mine

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### PR DESCRIPTION
**Pull request by thebest9178**
Closes #2256
Added blacklist in nuker
Minor formatting

### CODE REVIEW

**Comment by thebest9178** [comment]
A problem occurred configuring root project 'meteor-client'.
> Could not resolve all dependencies for configuration ':modCompileOnly'.
   > Could not resolve io.vram:canvas-fabric-mc119:1.0.+.

I don't think that's the fault of this pr

**Comment by MineGame159** [comment]
Why did you remove the bounding box and broken blocks comments?

**Comment by thebest9178** [comment]
I don't see it as being useful just clutter and a potential cause for confusion when someone assumes it's a separate category because no other module does that

**Comment by thebest9178** [comment]
Want me to put it back?

**Pull request merged**
