### PR TITLE
Make packet mine block class public

### PR DESCRIPTION
**Pull request by maxsupermanhd**
Make `MyBlock` accessible so other modules and addons can use it too.

I am currently working on villager trade rolling addon and I don't really want to copypaste packet mine basically.

### CODE REVIEW

**Comment by MineGame159** [comment]
You realise it depends on settings from Packet Mine.

**Comment by MineGame159** [comment]
And now more specifically to your use case, use `BlockUtils.breakBlock()`, call it from `TickEvent.Pre` every tick until the block is gone. And if the user wants to packet mine they can just enable the module.

**Comment by maxsupermanhd** [comment]
But @MineGame159, what is the best method to check that block is broken? Let's assume I spammed `BlockUtils.breakBlock()` but how can I stop and realize that it is broken?

**Comment by MineGame159** [comment]
If its air

**Pull request closed without merging**
