### PR TITLE
Add .give command

### PR DESCRIPTION
**Pull request by Octoham**
.give <item> <amount>
supports nbt
thats it thanks!

### CODE REVIEW

**Comment by Octoham** [comment]
the syntax is 
.give item amount

**Comment by seasnail8169** [comment]
Could you firstly rewrite that logic so its actually logical, all you need to do is loop through slots and check if they are empty, you could even use InvUtils. Secondly I don't see the point of having this method in Utils anyway you can just have it in the command class.

**Comment by seasnail8169** [comment]
Oh and also remove the extra files that eclipse added

**Comment by C10udburst** [comment]
I guess you've changed your mind since #247

**Comment by Wide-Cat** [comment]
kek cloud throwing shade

**Comment by Wide-Cat** [comment]
also whats with the eclipse stuff? Is it adding those files automatically or something? sorry if it's a dumb question but i don't use eclipse so idk this stuff

**Comment by AstroOrbis** [comment]
Eclipse and Idea (and others too) add configuration files and run files. Normally .gitignore takes care of them, but it didn't in this case.

**Comment by seasnail8169** [comment]
> I guess you've changed your mind since #247

The idea of an nbt argument seems slightly more useful. I was going to look at reintroducing it since im not sure why it was removed.

**Comment by Octoham** [comment]
> Oh and also remove the extra files that eclipse added

Could you add `.settings` to the gitgnore for eclipse users?

**Comment by Octoham** [comment]
wait gotta relove some eclipse files lmao

**Comment by Octoham** [comment]
done

**Comment by Octoham** [comment]
there
(oh and just keep the `//Created by Octoham 16/04/2021`)

**Comment by C10udburst** [comment]
I think you need to add NBT support back or @seasnail8169 won't merge. `ItemStackArgumentType` has support for NBT data you just need a different way to create the `ItemStack` (you should use `getItemStackArgument`)

**Comment by Octoham** [comment]
lemme test the build to make sure it works

**Comment by Wide-Cat** [comment]
@Octoham any updates?

**Comment by Octoham** [comment]
Not really, game crashes every time i use the command and i have no idea what to fix.De : Wide-CatEnvoyé le :Thursday, April 22, 2021 12:38 PMÀ : MeteorDevelopment/meteor-clientCc : Octoham; MentionObjet :Re: [MeteorDevelopment/meteor-client] Add .give command (#515) @Octoham any updates?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by seasnail8169** [comment]
swag

**Comment by Octoham** [comment]
emails am i right?

**Comment by Octoham** [comment]
i would like to know the issue with my version of the command

**Pull request merged**
