### PR TITLE
Made an integrated book dupe command :)

### PR DESCRIPTION
**Pull request by AstroOrbis**
Why not? Keeps people from downloading [this](https://github.com/MeteorDevelopment/meteor-book-dupe-addon/), and keeps everything nice and integrated!

### CODE REVIEW

**Comment by seasnail8169** [comment]
Firstly, why is there a github action in there lol.
Secondly, why do you think we created the addon? There is clearly a reason we didn't add this to mainline Meteor.

**Comment by AstroOrbis** [comment]
1. Because for SOME REASON the package net.minecraft doesn't show as a REAL GODDAMN thing on my system!
2. It was mostly just to have a bit of fun, and it was a request from someone from the Horizon team... any ideas of commands I can make because I'm bored? lmao

**Comment by seasnail8169** [comment]
"To have a bit of fun" you realise that all you did is uselessly pasted my code from one place to another. I don't see any reason for this at all. Also i don't have a clue what you are talking about with the Minecraft package but whatever, I'm not going to merge this.

**Comment by AstroOrbis** [comment]
allright, ill just add stuff to this because *why not*

**Comment by AstroOrbis** [comment]
and hey, having a bit of fun is having a bit of fun, don't judge me

**Comment by seasnail8169** [comment]
I'm not judging you, I am responding to your pull request? I dont know what you expected?
Are you perhaps unfamiliar with how pull requests, or contributing to projects, works?

**Comment by supakeks** [comment]
I don't see the point in this when
1. The dupe is insanely outdated, it works literally nowhere except vanilla servers
2. There's an add-on for it already which is mentioned in both #support and everytime someone asks for the dupe

**Comment by AstroOrbis** [comment]
I'm also trying to make an autodupe *module* with most methods... and if people don't want it, they don't use it! For me, the books are super OP because when used properly they can wipe entire chunks.

**Comment by supakeks** [comment]
There's no active book dupes lol

**Comment by AstroOrbis** [comment]
There are a few...

**Comment by AstroOrbis** [comment]
unpatched on certain servers

**Comment by supakeks** [comment]
No there aren't
the .d dupe only works on vanilla servers

**Comment by seasnail8169** [comment]
> I'm also trying to make an autodupe _module_ with most methods... and if people don't want it, they don't use it! For me, the books are super OP because when used properly they can wipe entire chunks.

The problem with this, as you may not be aware of, is that if we add a feature that does not work very often or is patched on many servers, it's not simply a case of "don't use it". We get many many support tickets, DMS, pings and even emails asking for support and many of these tend to be around these features (e.g the automountbypass and book dupes). This is why i chose to make them addons, this way people only see it if they directly look for it resulting in less people who don't understand what it is, asking for help using it when its not applicable in this situation.

**Comment by AstroOrbis** [comment]
allright, ill just make a full dupe module i guess

**Comment by seasnail8169** [comment]
Please read what i wrote, you are really missing the point…

**Comment by AstroOrbis** [comment]
oh i get it now, thanks...






i still kinda wanna work on something for meteor so what should I do :p

**Comment by seasnail8169** [comment]
Have a look at the [issues](https://github.com/MeteorDevelopment/meteor-client/issues) section to see what needs to be worked on in the client.

**Comment by AstroOrbis** [comment]
allright thanks!

**Comment by Titaniumtown** [comment]
bruh what happened here :laughing:

**Comment by seasnail8169** [comment]
> bruh what happened here :laughing: 

?

**Comment by AstroOrbis** [comment]
> bruh what happened here 😆

?

**Pull request closed without merging**
