### PR TITLE
Speed Mine

### PR DESCRIPTION
**Pull request by fluse1367**
Should be clear.
- Normal Mode (modifies final breaking speed value)
- Haste 1&2 Mode
- Packet Mode

### CODE REVIEW

**Comment by MineGame159** [comment]
Packet mine is already a separate module

**Comment by fluse1367** [comment]
Look up the code, it's a different thing

**Comment by MineGame159** [comment]
I see the code is not the same but the description is the same

**Comment by fluse1367** [comment]
Wdym

**Comment by MineGame159** [comment]
"While in PACKET mode, hitting a block %sonce%s will eventually break it." that is what you send in chat when enabling packet mod  and it is exactly what packet mine module does

**Comment by fluse1367** [comment]
Yea ok i got the point, but as far as i tested it speedmine in packet mode is still faster than packetmine. my fault if i'm wrong ¯\_(ツ)_/¯

**Comment by MineGame159** [comment]
How does the packet mode work? Looking at the code and all I see it doing is sending a STOP_DESTROY_BLOCK player action packet once the block break progress is greater or equal to 1.

**Comment by fluse1367** [comment]
I think you overlooked the return statement: it will immediately send the STOP_DESTROY_BLOCK action _unless_ the break progress is greater or equal to 1

**Comment by MineGame159** [comment]
Oh yeah, sorry, So then its doing the same thing as packet mine. Spamming the server with START and STOP packets, it propably just felt faster but werent.

**Comment by fluse1367** [comment]
lmao, prolly. should i remove it then or rather packet mine (i think its clearer if its all in the same module)

**Comment by squidoodly** [comment]
Why would you move packet mine to speed mine when it doesn’t make it faster?

**Comment by fluse1367** [comment]
True, my bad. I'm gonna remove packet mode then

**Pull request merged**
