### PR TITLE
Add regex filtration to BetterChat

### PR DESCRIPTION
**Pull request by StormyBytes**
Wide suggestion

### CODE REVIEW

**Comment by seasnail8169** [comment]
very wide

**Comment by RickyTheRacc** [comment]
What is regex filtration

**Comment by seasnail8169** [comment]
bebabebabeabe

**Comment by MineGame159** [comment]
1. Look at any other list setting, you need to override the reset method and recreate the list.
2. In my opinion the string list setting should just be inline in the gui like it was before and a button that opens new screen.
3. While you at it can you also implement the list setting to other modules

**Pull request merged**
