### PR TITLE
MouseMixin: use Inject instead of Redirect

### PR DESCRIPTION
**Pull request by Cynosphere**
Fixes crash with other mods mixing into Mouse

### CODE REVIEW

**Comment by seasnail8169** [comment]
Did you even test this?

**Comment by seasnail8169** [comment]
It wont compile

**Comment by Cynosphere** [comment]
And that's what I get for being lazy and not cloning the repo locally...

**Comment by seasnail8169** [comment]
Mfw pr but doesn't even test if it compiles let alone if it works

**Comment by Cynosphere** [comment]
...don't even give me time to fix it in another commit ok

**Comment by Cynosphere** [comment]
just keep it fucking broken then cocky fuckwad

**Comment by seasnail8169** [comment]
Lmfao it's clearly a completely thoughtless pull request and given that, I don't think it's me thats in the wrong.
Also its not like PRs can't be repopened if they are fixed lol.

**Comment by seasnail8169** [comment]
Sure if you made some mistakes or didn't fit our style you could correct this but this pr is literally just incorrect, like it just can't work like that and you clearly didn't test or maybe even think about this considering you literally left non existent references in the code and didn't notice.

**Pull request closed without merging**
