### PR TITLE
Added Macro execute command

### PR DESCRIPTION
**Pull request by DesiCow**
Syntax:
`.macro <macro-name>` to execute the macro

### CODE REVIEW

**Comment by arlomcwalter** [comment]
macros triggering macros :trollface:

**Comment by DesiCow** [comment]
> macros triggering macros :trollface:

That's the motivation behind this pr :trollface: 

> why did you re order the tab bar

So MacroCommand can access Macros, but it doesn't affect the order of tabs ingame, i.e. tabs are still displayed in [same order](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/gui/tabs/Tabs.java#L19-L26).

**Comment by MineGame159** [comment]
I am failing to understand the reason behind the reorder.

**Comment by DesiCow** [comment]
> I am failing to understand the reason behind the reorder.
> 
> EDIT: Oh I think I see why, when the command is created the `MacroArgumentType` is loaded for the first time, so the static fields are initialized, which accesses the `Macros` class. Anyways, the examples should probably be recomputed every time it is called, or atleast cached because for first time users they won't have any macros.

Thanks for the review. And yes, thats the reason for reorder.

**Pull request merged**
