### PR TITLE
Enhance VeinMiner

### PR DESCRIPTION
**Pull request by o0sh4d0w0o**
## Enhance VeinMiner

- [ ] Bug fix
- [x] New feature

## Description

Add two new options : 

-  Under mining ; Avoid players to mine under their y position
-  Visibility check ; Mine blocks only available on line of sight

Rework a bit distance check to maximize avoiding to mine too far away (but it probably can be much enhanced to be more accurate)

Update on Utils to add raycastBlock and breakBlock overload.

# How Has This Been Tested?

Built tested and used on my local server with NCP active

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by arlomcwalter** [comment]
did you really delete the whole pr template lol

**Comment by RacoonDog** [comment]
i would too i hate the template

**Comment by arlomcwalter** [comment]
> i would too i hate the template 

why

**Comment by arlomcwalter** [comment]
i added it because people usually provide fuck all info about their prs

**Comment by Wide-Cat** [comment]
Can you rename the settings to be more descriptive, and also consistent with the standard naming scheme. For example, 'Under mining' could be 'mine-under-player' or something similar

**Comment by o0sh4d0w0o** [comment]
> Can you rename the settings to be more descriptive, and also consistent with the standard naming scheme. For example, 'Under mining' could be 'mine-under-player' or something similar

Sure, i'll do this tomorrow

**Comment by Paddyk45** [comment]
What the hell is this

**Comment by Wide-Cat** [comment]
kek

**Comment by SylveonBottle** [comment]
💀

**Comment by o0sh4d0w0o** [comment]
Forgot I had this opened before doing my merge sorry.

**Comment by BDARmech** [comment]
Did it work?

**Comment by o0sh4d0w0o** [comment]
That's just correctly updated my forked master and fucked up this PR, however it was opened since a while without implementation so far that i didn't remember i've done it so that's not a big deal ^^.

**Pull request closed without merging**
