### PR TITLE
Initial cleanup

### PR DESCRIPTION
**Pull request by bramceulemans**

### CODE REVIEW

**Comment by MineGame159** [comment]
What

**Comment by seasnail8169** [comment]
lmao

**Comment by seasnail8169** [comment]
@MineGame159 90% of this is just intellijs code cleanup feature, the rest is mostly bullshit

**Comment by seasnail8169** [comment]
@bramceulemans clicking Analyze > Code Cleanup is not really a contribution you are just siimply disrupting the regular standards we use. I'm not gonna accept anything that was just you clicking auto cleanup, especially considering it doesn't follow any of the regularities that we use normally in this project and our other projects.

**Comment by bramceulemans** [comment]
Sorry, I didn't mean to submit it already.

**Comment by seasnail8169** [comment]
ok

**Pull request closed without merging**
