### PR TITLE
Rewrote AutoSmelter (2)

### PR DESCRIPTION
**Pull request by Thunderkill**
This is an update for #1237

This PR now includes fixes for the settings saving issue, and contains an updated description

### CODE REVIEW

**Comment by MineGame159** [comment]
Can you make it not display any items in main menu? Because now they can select for example stone as fuel item while in menu and when they go into a world and open the list the stone will be hidden by the filter but it will still remain selected in the list.

**Comment by Thunderkill** [comment]
> Can you make it not display any items in main menu? Because now they can select for example stone as fuel item while in menu and when they go into a world and open the list the stone will be hidden by the filter but it will still remain selected in the list.

Well, i tried that; but then it wouldn't properly load the items at all

**Comment by MineGame159** [comment]
Well then you did something wrong, I don't see a reason why it shouldn't work

**Comment by Thunderkill** [comment]
> Well then you did something wrong, I don't see a reason why it shouldn't work

Well, i can't figure what i've done wrong. I mean it should work but it doesn't, it just won't load the items.

My assumption was that the item won't be loaded as it won't fit the filter on init

**Comment by MineGame159** [comment]
The filter is ran every time the screen is opened

**Comment by Thunderkill** [comment]
> The filter is ran every time the screen is opened

Actually the filter **is** run on startup:
ItemListSetting.java line 83


After some testing around, i settled on just showing everything. As the module itself checks the item again if it's smeltable or can be used as a fuel.

And after restarting the client it will remove the faulty items that should not be in the item lists.

**Comment by MineGame159** [comment]
Yes what you are saying is correct but this filter is still ran every single time when you open the screen

**Comment by Thunderkill** [comment]
> And after restarting the client it will remove the faulty items that should not be in the item lists.

Actually nevermind about this part

**Comment by Thunderkill** [comment]
> Done. Is there anything you want to do or can I merge.

You can merge

**Pull request merged**
