### PR TITLE
Better Tooltips, Inventory Tweaks language support

### PR DESCRIPTION
**Pull request by Nekiplay**
## Type of change

- [ ] Bug fix
- [x] New feature

## Description

Support for different languages for Better Tooltips and Inventory Tweaks

## Related issues

None

# How Has This Been Tested?

image

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Review by RacoonDog — CHANGES_REQUESTED** [review]
- dont put formatting codes in the language files, do text styling in code
- add 'meteor-client' somewhere in all of the translation keys
- dont do `Text.literal(I18n.translate())`, use `Text.translatable()`

**Comment by Nekiplay** [comment]
> * dont put formatting codes in the language files, do text styling in code (`Text.translatable()` can also take styled `Text` objects as template arguments)

As far as I'm concerned they should be there as it allows resourcepack creators to edit colors

**Comment by duydzmc12** [comment]
Ccc

**Comment by Nekiplay** [comment]
Now has in Meteor+

**Pull request closed without merging**
