### PR TITLE
Dynamic font loading

### PR DESCRIPTION
**Pull request by Nippaku-Zanmu**
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

Dynamic loading of fonts makes it possible to render Chinese fonts normally

## Related issues

#4372 #333 #1854

# How Has This Been Tested?

https://github.com/user-attachments/assets/5b38bd56-f1ba-4515-b36b-723a934fd0e2

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Review by watchingfun — APPROVED** [review]

**Comment by watchingfun** [comment]
image
大佬，为啥我拉下你的代码跑是乱码啊

**Comment by Nippaku-Zanmu** [comment]
> image 大佬，为啥我拉下你的代码跑是乱码啊

请使用支持中文的字体文件 流星端的默认字体是**不支持中文**的 你可以下载一个支持中文的字体 例如HP Simple Hams

**Comment by watchingfun** [comment]
确实是这个问题，换支持中文的字体就好了

**Comment by lyy2182** [comment]
过去多久了还不拉取？

**Comment by Nippaku-Zanmu** [comment]
> 过去多久了还不拉取？

目前可以用用我的插件修复中文渲染 但是效果没有这个好

**Pull request closed without merging**
