### PR TITLE
little code clean up and fixes

### PR DESCRIPTION
**Pull request by WERooo**
fixes bugs like #2202
fixes outline bottom line not rendered when only one module enabled
cleaned up some modules code

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
Minegame?

**Comment by MineGame159** [comment]
This PR breaks XRay with Fabric Api (no Sodium). Apart from that looks good.

**Comment by WERooo** [comment]
in docs to mixin it says that remap is default to true

**Comment by MineGame159** [comment]
Yes but if remap is set to false on the class itself the injections are false by default too.

**Comment by WERooo** [comment]
i just seen previous commits and didnt check that. thanks.

**Pull request merged**
