### PR TITLE
Vertical Range For Scaffold

### PR DESCRIPTION
**Pull request by Declipsonator**
now? :trollface:

### CODE REVIEW

**Comment by seasnail8169** [comment]
Never :trollface:

**Comment by Declipsonator** [comment]
noooooo

**Comment by Declipsonator** [comment]
oh shit

**Comment by Declipsonator** [comment]
thats gonna fail

**Comment by Declipsonator** [comment]
I'll fix any other problems in the morning

**Comment by Declipsonator** [comment]
(my morning

**Comment by Declipsonator** [comment]
time to wait another month

**Comment by Wide-Cat** [comment]
inb4 never merged again

**Comment by Declipsonator** [comment]
when

**Comment by Declipsonator** [comment]
you know what, I'm gonna count every day this has been open

**Comment by Declipsonator** [comment]
1

**Comment by Declipsonator** [comment]
2

**Comment by Declipsonator** [comment]
3

**Comment by Declipsonator** [comment]
4

**Comment by Declipsonator** [comment]
5

**Comment by asdffdsdaf** [comment]
6 and 7

**Comment by Declipsonator** [comment]
yes

**Comment by Declipsonator** [comment]
when

**Comment by asdffdsdaf** [comment]
not today :smirk_cat:

**Comment by Wide-Cat** [comment]
The eternal pr, kek

**Comment by Cypphi** [comment]
8, 9, 10, 11

**Comment by asdffdsdaf** [comment]
> 8, 9, 10, 11

shut the fuck up you are wrong

**Comment by BobIsMyManager** [comment]
> > 8, 9, 10, 11
> 
> shut the fuck up you are wrong

Lmao (12, 13, 14, 15)

**Comment by Declipsonator** [comment]
when

**Comment by BobIsMyManager** [comment]
ur mom

**Comment by Declipsonator** [comment]
:weary:

**Comment by AstroOrbis** [comment]
19

**Review by AstroOrbis — APPROVED** [review]

**Comment by Declipsonator** [comment]
:weary:

**Comment by AstroOrbis** [comment]
kek

**Comment by BobIsMyManager** [comment]
Lol

**Pull request closed without merging**
