### PR TITLE
Resolves #1063

### LINKED ISSUE #1063: [Suggestion] Better spam delay
**Describe the feature**
Improve the delay setting of 'spam'. It doesn't allow for decimals, it only allows integers which is quite annoying when trying to configure it to match the antispam limit as closely as possible. 
Either expand it so instead of running via seconds, run via ticks. (And adjust the slider to accomodate for higher values obviously) Or allow decimals.

### PR DESCRIPTION
**Pull request by a-couple-objects**
coding on da fone

### CODE REVIEW

**Comment by Wide-Cat** [comment]
ez coding on da fone

**Comment by seasnail8169** [comment]
bad

**Comment by seasnail8169** [comment]
wont work

**Comment by supakeks** [comment]
why

**Comment by a-couple-objects** [comment]
why not

**Comment by seasnail8169** [comment]
check your code, see the obvious mistake

**Comment by seasnail8169** [comment]
This will mean it will use tick delay for the first message and then seconds from then on

**Comment by seasnail8169** [comment]
just dont pr from the phone please

**Pull request closed without merging**
