### PR TITLE
Search module limit

### LINKED ISSUE #1780: [Suggestion]
### Describe the feature

A culling feature for the module:search it would be nice because u can lag if u are trying to find something which is kinda alot in the area and culling would be very nice to have in that case

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**
no more lags lol (closes #1780)

### CODE REVIEW

**Comment by RacoonDog** [comment]
w pr

**Comment by I-Got-You-Dead** [comment]
> w pr

fr

**Comment by MineGame159** [comment]
There is a very big problem with this. In the screenshot I am searching for diamonds and set my limit to 1000 (or even the default 10000 does the trick) and you can see it searched the chunks from furthest to closest which it should be the other way around. Also when I move around it should rescan the closest chunks because right now even if I move those 1000 blocks will stay there until they are unloaded and no new diamonds will be shown.
image

I think a better way to approach this is to search every chunk as it does right now and limit the amount of chunks it renders.

**Comment by ThebestkillerTBK** [comment]
> There is a very big problem with this. In the screenshot I am searching for diamonds and set my limit to 1000 (or even the default 10000 does the trick) and you can see it searched the chunks from furthest to closest which it should be the other way around. Also when I move around it should rescan the closest chunks because right now even if I move those 1000 blocks will stay there until they are unloaded and no new diamonds will be shown.
> I think a better way to approach this is to search every chunk as it does right now and limit the amount of chunks it renders.

It seems hard to render the closest chunks and if you check the limit on render it will cause lag

**Comment by MineGame159** [comment]
Why would it be hard or slow? In the render method before it loops over the chunks you just need to sort all of the chunks and then have a loop with an if statement to break out of the loop if the number of blocks rendered increased over the limit. And for the lag part, sorting the chunks is just a matter of calculating the distance to the camera, and since you are only comparing the values you can use the squared version to avoid square root operations.

**Comment by I-Got-You-Dead** [comment]
Sadage

**Pull request closed without merging**
