### PR TITLE
Add trajectories to already fired projectiles

### PR DESCRIPTION
**Pull request by C10udburst**
also exposes accurate argument to the user

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
Vector

**Comment by C10udburst** [comment]
> Vector

what?

**Comment by I-Got-You-Dead** [comment]
Ayo aren’t u part of anti cope?

**Comment by C10udburst** [comment]
> Ayo aren’t u part of anti cope?

yeah

**Comment by I-Got-You-Dead** [comment]
Sick

**Pull request merged**
