### PR TITLE
1.20.5/.6 update

### PR DESCRIPTION
**Pull request by Big-Iron-Cheems**
## Type of change

- [ ] Bug fix
- [X] New feature

## Description

Update Meteor for 1.20.5/.6
The 1.20.5 compatibility will be dropped if necessary later on.

## Related issues

None.

# How Has This Been Tested?

This is still WIP, it builds and runs, but could have some bugs.

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [ ] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by ModxVoldHunter** [comment]
gonna build the jar and test to see if there is any bugs before any changes are made

**Comment by Wide-Cat** [comment]
sure more eyes looking for bugs is always welcome

**Comment by ModxVoldHunter** [comment]
> sure more eyes looking for bugs is always welcome

i don't see anything wrong, looks good to me.

**Comment by ModxVoldHunter** [comment]
nvm when using meteor and placing anything that isn't cobblestone makes the placing stone sound

**Comment by ModxVoldHunter** [comment]
> nvm when using meteor and placing anything that isn't cobblestone makes the placing stone sound

and i found out it was "No Ghost Blocks" causing the issue

**Comment by DataGoblin** [comment]
There is a rendering issue with waypoints. They are either stickied randomly in a corner on the HUD or not visible.

**Comment by RedCarlos26** [comment]
@DataGoblin was this fixed?

**Comment by Wide-Cat** [comment]
> @DataGoblin was this fixed?

Minegame is looking at it

**Comment by ModxVoldHunter** [comment]
Was the bug I mentioned, fixed or being looked at?

**Comment by Wide-Cat** [comment]
Yes

**Comment by phpmypython** [comment]
What are the chances of this getting merged soon?

**Comment by Big-Iron-Cheems** [comment]
> What are the chances of this getting merged soon?

We don't have an ETA, It'll be out once we say it's ready.
There's still some things we want to look at.

**Comment by Wide-Cat** [comment]
PSA we are going to wait until 1.20.6 gets released before we merge this and update, since the versions are near identical. Unless more issues are found, Mojang will probably release it around Tuesday next week, so the expected timescale is this will likely be merged either on Tuesday or Wednesday (depending on when Mojang releases).

**Comment by ModxVoldHunter** [comment]
> PSA we are going to wait until 1.20.6 gets released before we merge this and update, since the versions are near identical. Unless more issues are found, Mojang will probably release it around Tuesday next week, so the expected timescale is this will likely be merged either on Tuesday or Wednesday (depending on when Mojang releases).

would you like someone to make a preview version of meteor on a minecraft test snapshot to see if it will work?

**Comment by RedCarlos26** [comment]
I'm trying to add a commit but it doesn't let me

**Pull request merged**
