### PR TITLE
Create AutoPot.kt

### PR DESCRIPTION
**Pull request by LeiDonn**

### CODE REVIEW

**Comment by Declipsonator** [comment]
kotlin 🤔

**Comment by MineGame159** [comment]
1. We are not working with kotlin nor accept prs with it.
2. The formatting is horrible.

**Comment by seasnail8169** [comment]
@MineGame159 he literally just ran "convert java class to kotlin" on gildeds autopot

**Comment by GildedS** [comment]
Bruh that's literally my autopot. Stop skidding and start making your own modules

**Comment by GildedS** [comment]
> bias

Cope

**Comment by Lncvrt** [comment]
> 1. We are not working with kotlin nor accepting prs with it.
> 2. The formatting is horrible.

LMAO THE FORMATTING IS ABSOLUTELY WILD

**Pull request closed without merging**
