### PR TITLE
More customizable HandView

### PR DESCRIPTION
**Pull request by DiOnFire**
Now you can change the rendering of the hands individually
aaaaaaaaa
.

### CODE REVIEW

**Comment by RedCarlos26** [comment]
That's awsome

**Comment by Vitalasy** [comment]
epic

**Comment by RickyTheRacc** [comment]
Merge please

**Comment by RedCarlos26** [comment]
^

**Comment by DiOnFire** [comment]
@MineGame159

**Comment by Declipsonator** [comment]
Didn't this overwrite #1973

**Comment by RedCarlos26** [comment]
It probably did

**Comment by MineGame159** [comment]
It didn't

**Comment by RedCarlos26** [comment]
Oh nice

**Pull request merged**
