### PR TITLE
Optimised imports ¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by seasnail8169**
Its not even useful but i saw it in intellij and it looked cool so here it is :yes:

### CODE REVIEW

**Comment by squidoodly** [comment]
Most of this is just moving imports around. I don’t really see the point in merging this.

**Comment by seasnail8169** [comment]
i mean i did kinda say that i just meant that there were isn’t really any reason not to, a fair amount is removing imports that aren’t used so i see it as more beneficial than not.

**Comment by MineGame159** [comment]
Im fine with merging it, just do ctrl+shift+o (optimize inports) in every file you are currently working on

**Comment by seasnail8169** [comment]
FYI it was automatically done my IntelliJ, i didn’t just move them around for fun lol

**Comment by MineGame159** [comment]
I know, just saying to do it per file when you are working on them

**Pull request merged**
