### PR TITLE
Added Player Coordinates to PlayersHUD and fixed a bug.

### PR DESCRIPTION
**Pull request by StormyBytes**
Player Coordinates Preview:
image

The bug was, when there isnt any other player (other than self) in render distance, the PlayersHUD bounding box will have a width of 0. Meaning it cannot be moved or selected in the HUD editor.

### CODE REVIEW

**Comment by seasnail8169** [comment]
Can you format them to whole numbers please.

**Comment by StormyBytes** [comment]
Whoops i used `Double.toString` instead of `Long.toString`

**Comment by seasnail8169** [comment]
I don't like the way you have done this tbh.

**Comment by StormyBytes** [comment]
My apologies, I am quite new to minecraft modding. Is there any thing I could do to improve it?

**Comment by supakeks** [comment]
> I don't like the way you have done this tbh.

what doesn't? the code or how it looks in-game? since in-game I can't think of any other way to do it and this looks decent imo, would maybe make the coords color different so it's easy to know what's a username and what are coords

**Comment by ekcire06** [comment]
im with seasnail on this one. it just seems unneccesary, and to use it youd have to cross reference it with your cords and figure out what direction your facing. would be too hard to use to be useful. tracers are already perfect for showing where a player is in relation to you, and are very intuitive to use.

**Comment by RedCarlos26** [comment]
The bug fix should be implemented tough

**Comment by MineGame159** [comment]
I would make the coords a different color than the names

**Comment by seasnail8169** [comment]
The coordinates should use the secondary HUD color like almost every other HUD element. Also can you send a screenshot of how this looks with your changes.

**Comment by seasnail8169** [comment]
The coordinates should use the secondary HUD color like almost every other HUD element. Also can you send a screenshot of how this looks with your changes.

**Comment by StormyBytes** [comment]
image
might need to implement antibot to playershud...

**Comment by seasnail8169** [comment]
That looks awful, i will rewrite it when i get home.

**Pull request closed without merging**
