### PR TITLE
added a sync option to crystalaura

### PR DESCRIPTION
**Pull request by ekcire06**
sync is great and all, but it does slow down ca significantly if your ping is high. so I added an option for it. I also renamed cancel crystal to sync mode. its enabled by default btw.

### CODE REVIEW

**Comment by supakeks** [comment]
What is the point of this

**Comment by MineGame159** [comment]
On an unrelated note, what the actual fuck is that formatting

**Comment by ekcire06** [comment]
the point of this is because sync (even on hit mode) can slow down crystalaura (by about 1/3rd in my tests at 130 ping, I tested it by seeing how long it took to eat through a stack of crystals, and then reloged after to make sure there were no ghostplaces.), so I just added an option to use the old desyncy but faster crystalaura. 

sorry about the formatting lmao, im kinda new to this.

**Comment by supakeks** [comment]
There is literally 0 speed difference, it looked faster before because the crystals weren't synced, making it look faster when looking at the crystals in your hotbar

**Comment by ekcire06** [comment]
what ping are you testing at? I tried to ensure that wasnt a factor by measuring how long it took to use a set amount of crystals instead of looking at how fast the numbers were moving in hotbar...

**Comment by supakeks** [comment]
130
The OnHit and OnSound have nothing to do with syncing, all it's for is when to remove the crystal from the world

and again, there's 0 speed difference with the new syncing

**Comment by ekcire06** [comment]
but the crystal has to be removed for it to try to place another one where the previous one was

**Comment by supakeks** [comment]
Yes and that's exactly what CrystalAura does with OnSound

OnHit is stupid and breaks ca on ncp servers, I don't know why it's still an option, there's a way to remove the crystal on sound without breaking ca but I still can't figure that out on 1.16

**Comment by ekcire06** [comment]
I tested this on avas.cc, a server without ncp or any other ac... that probably explains the difference in results we are getting.

**Comment by supakeks** [comment]
OnHit is just bad, there's ways to make ca even faster than onHit without actually desyncing, plus when you attack a crystal it removes from the world (server side) after 1 tick afaik, and since onhit removes it from the world (client side) as soon as you hit it it just creates desync

**Comment by ekcire06** [comment]
how about I make so instead of a sync setting I make it a "instantly" option of cancelcrystal and put a warning in the description that it will cause signifigant desync?

**Comment by ekcire06** [comment]
for some reason github is being weird with my formatting. shows up as normal and sensible in github desktop and my ide, but messes it up when I commit it. im gonna try to fix it.

**Comment by seasnail8169** [comment]
jesus christ please look up java formatting standards

**Comment by ekcire06** [comment]
Screenshot (325)

what it looks like in my ide vs on github lmao

**Comment by ekcire06** [comment]
oops. didnt mean to commit that gradle thing lmao

**Comment by ekcire06** [comment]
im just gonna close this garbage

**Pull request closed without merging**
