### PR TITLE
Added the option to exclude swords from auto tool (and Added the option to override distance colors of friends with the friend colors)

### LINKED ISSUE #2963: AutoTool avoid sword option
### Describe the feature

I don't use AutoTool because it uses up my sword, would be nice if there was an option to exclude any given tool(s).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

### PR DESCRIPTION
**Pull request by I-Got-You-Dead**
Closes #2963

### CODE REVIEW

**Comment by MineGame159** [comment]
The setting is reversed.

**Comment by I-Got-You-Dead** [comment]
💀 I’ll have it fixed today

**Comment by I-Got-You-Dead** [comment]
Git didnt make a new fork, instead committing on this pr

**Comment by I-Got-You-Dead** [comment]
So yea, 2 things, 1 pr

**Comment by MineGame159** [comment]
Can you fix the conflict (sorry the other PR was made sooner :trollface:) and while you are at it also put the `getColorFromDistance` to some utils class so it doesn't need to be duplicated there.

And just as a tip on how to properly do PRs, you are not supposed to make a new fork if you want to make multiple PRs. The cleanest way to do it is to never commit anything to the main branch of your fork, just keep that synced with upstream. And then you make a new branch for every PR.

**Comment by I-Got-You-Dead** [comment]
> Can you fix the conflict (sorry the other PR was made sooner :trollface:) and while you are at it also put the `getColorFromDistance` to some utils class so it doesn't need to be duplicated there.
> 
> And just as a tip on how to properly do PRs, you are not supposed to make a new fork if you want to make multiple PRs. The cleanest way to do it is to never commit anything to the main branch of your fork, just keep that synced with upstream. And then you make a new branch for every PR.

1: Yea sure, I was planning on waiting till it was merged to fix it.
2: I was thinking maybe I could put ‘getColorFromDistace’ in entity utils or something like that.
3: Thx for the tip

**Comment by I-Got-You-Dead** [comment]
ima just completely redo this

**Pull request closed without merging**
