### PR TITLE
Invalid public key fix

### LINKED ISSUE #2598: [Bug] Switching To Microsoft Account Causes Error Joining Servers
### Describe the bug

Joining any multiplayer server on Meteor 0.5.1 after changing microsoft accounts via the account switcher causes the error shown below
IXZUUwGG

Account switcher that I'm referencing for anyone unfamiliar
xeYg3iPq

### Steps to reproduce

```bash
1. Open Minecraft w/ Meteor
2. Click "Multiplayer"
3. Click "Accounts" in top right
4. (if a second account isn't already linked) Link account by clicking "Microsoft"
5. Click "Login" next to another account
6. Press "esc/escape" on your keyboard
7. Select any multiplayer server
8. Error: "Invalid signature for profile public key. Try restarting your game."
```

### Meteor Version

0.5.1 (0.5.0 works)

### Minecraft Version

1.19.1 (1.19 works, this is likely due to microsoft's chat changes in 1.19.1)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

### PR DESCRIPTION
**Pull request by Soda5601**
Reset everything about account when trying to change alt
fixes #2598 and #3001

### CODE REVIEW

**Comment by ThebestkillerTBK** [comment]
Tested, no warnings will appear now.

**Comment by Wide-Cat** [comment]
I just tested this on a local paper server with enforce-secure-profile=true and it doesnt seem to work. Joined the server fine on one account, then swapped to another and got the invalid signature error. Continued to get that error after swapping back to the original account.

**Comment by ThebestkillerTBK** [comment]
There was no issue when I logged in a microsoft account. You just chat normally and wont be kicked

**Comment by Wide-Cat** [comment]
did you try starting the game with one account and then swapping to another? I promise that it wasnt working for me.

**Comment by Wide-Cat** [comment]
resolved as of #3434

**Pull request closed without merging**
