### PR TITLE
Add autosave feature for profiles

### PR DESCRIPTION
**Pull request by SnivyLlama**
Ok this was like, the one thing bothering me about meteor so I decided to fix it myself
Lemme know if I should change it

### CODE REVIEW

**Review by SIMULATAN — CHANGES_REQUESTED** [review]
👍 Very cool but i'd also add a scheduled task to save it every x seconds because most of the time the issue is that the game crashes without you saving the config. Sessions on Servers can be long (2b2t for example) and thus this function wouldn't be called too often

**Comment by SnivyLlama** [comment]
Alright, I think I can get this done

**Comment by SnivyLlama** [comment]
Alright, I got it

**Comment by SnivyLlama** [comment]
Should I remake this pr with one pull request so that it's just one commit?

**Comment by SnivyLlama** [comment]
yeah ill do that

**Comment by SIMULATAN** [comment]
> Should I remake this pr with one pull request so that it's just one commit?

squash merge exists?

**Pull request closed without merging**
