### PR TITLE
Inventory Tweaks improvements

### LINKED ISSUE #1189: #1162 Re-write Auto Steal features [Suggestion]
2 modules:
Auto Steal
Auto Dump
This is the best way to do it because you must have different hotkeys to remain sane.

Both:
-whitelists for different kinds of containers. (shulkers, enderchests, etc)
-whitelists for what items to steal. (you don't want to steal 20 stacks of cobblestone)
-sliders for how fast you will steal/dump, should include a random slider too like it had before

Auto Dump: will only work if you open the chest and the module is enabled
-Option to Replenish stacks while dumping: while dumping, meteor will look for items in your the container you are using  and will attempt to replenish the items in your inventory and stack them up to 16/64 if it is a stackable item. 
-Alike items: should find items that share the same nbt and if it is whitelisted, should dump the items in that chest that fit with that item

Auto Steal:
-range slider (how far away from the chest do you need to be to auto steal)
-Option to open containers through walls. 

----
ignore mobs with chests on them? I think it is better to ignore them.

My previous suggestion was a complete ugly mess of ideas and did not make sense at all, forcing me to rewite it into a better suggestion that includes well written features.

### LINKED ISSUE #1699: [Suggestion]
### Describe the feature

Add possibility to select item to steal from chests.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### LINKED ISSUE #2401: [Bug]
### Describe the bug

Auto Steal in Inventory Tweaks does not auto steal on Chest open. The button works fine but the option to Auto Steal was confirmed broken by seasnail on Discord. Auto Dump works.

### Steps to reproduce

```bash
Enable Auto Steal under Misc>Inventory Tweaks>Auto Steal
```

### Meteor Version

0.4.9 (?)

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

### LINKED ISSUE #2428: inventory tweaks
### Describe the feature

can you add other storage blocks to the list of storage blocks that autos steal in inventory tweaks steals from. it doesn't steal from barrels at least I haven't checked any others other than chests

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### LINKED ISSUE #2466: [Suggestion] Items stealer
### Describe the feature

Please make an item filter for stealer, it's really useful for farming when you need to sort some specific item

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### LINKED ISSUE #2542: [Suggestion] Filter for Dump in the Inventory tweaks Module
### Describe the feature

I want to exclude my Hotbar from getting dumped into a chest.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### LINKED ISSUE #2662: [Suggestion]
### Describe the feature

to be able to steal a specific item from contaniers. ex if i want only golden apples i enable that in the module and then it will steal it from the chest

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### LINKED ISSUE #3340: Inventory steal and dump buttons are in the wrong location
### Describe the bug

This happened somewhere after version 1750. I assume an hope this is a bug and not a design change.

The old:
old

The new:
new

Please fix, thank you!

### Steps to reproduce

```bash
- Cleanly install the latest build in the stock launcher or a launcher of your choice
- Enable inventory tweaks
- Open a chest
```

### Link to crash report/log if applicable (https://mclo.gs)

_No response_

### Meteor Version

1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

### PR DESCRIPTION
**Pull request by DesiCow**
## Type of change

- [X] Bug fix
- [X] New feature

## Description

* Item Deleter button: Users can now quickly and silently destroy selected items without dropping them.
* Customizable buttons: Users can now individually customize and toggle each button to be displayed in containers.
* Now items in hotbar can be excluded for item dumper.
* Hopefully better buttons location
* Fixed an issue where items weren't dropping for the item stealer feature when rotation was disabled.

## Related issues

Closes #1189
Closes #1699
Closes #2401
Closes #2428
Closes #2466
Closes #2542
Closes #2662
Closes #3340

# How Has This Been Tested?

Tested on dedicated Paper server.
https://www.youtube.com/watch?v=yHb-BdqnbSg

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by RickyTheRacc** [comment]
I approve

**Comment by I-Got-You-Dead2** [comment]
Very swag pr

**Comment by Big-Iron-Cheems** [comment]
Based PR, I approve

**Comment by Wide-Cat** [comment]
When the items filter setting is set to 'None', I would assume that means the filer is disabled; however, it seems when it's set to none it filters every item, meaning the respective setting doesn't work at all. I would've thought for the default settings it would work for every item, and then from there you could customise the filter to your desire.

**Comment by DesiCow** [comment]
> When the items filter setting is set to 'None', I would assume that means the filer is disabled; however, it seems when it's set to none it filters every item, meaning the respective setting doesn't work at all. I would've thought for the default settings it would work for every item, and then from there you could customise the filter to your desire.

In my view, users may not want to risk losing their valuable items by accidentally clicking on the delete button, hence the reason for referring to the 'None' filter as the 'All' filter' and having it set to default

However, I believe that the 'None' or 'All' filters are essentially redundant. You can easily achieve the same results with whitelist and blacklist filters. So, in my opinion, the None/All filters may not be necessary and could be removed without any significant impact on the overall user experience.

Let me know your thoughts.

**Comment by Wide-Cat** [comment]
I think removing the None filter would probably be a decent idea. As you said, you can just do the same thing with the other filters.

**Comment by ThebestkillerTBK** [comment]
Why not replace all filter as a util?

**Review by BDARmech — APPROVED** [review]

**Comment by Wide-Cat** [comment]
Apparently this pr has merge conflicts. Can you resolve them so we can look at implementing this?

**Comment by DesiCow** [comment]
> Apparently this pr has merge conflicts. Can you resolve them so we can look at implementing this?

I'll have some free time over the weekend and will make the necessary updates.

**Comment by RedCarlos26** [comment]
@DesiCow please fix the conflicts 🙏

**Pull request closed without merging**
