### PR TITLE
Test commits, and if successfully built release as Artifact

### PR DESCRIPTION
**Pull request by Erisfiregamer1**
Pushes a built version of the mod to an artifact on every commit, if the CI check succeeds.

### CODE REVIEW

**Comment by seasnail8169** [comment]
Firstly, we use CircleCI for build tests and have for almost all of meteors life.
Secondly, meteor is a 1.17.1 Minecraft mod and hence requires Java 16 to build, you are trying to use Java 11 for this which wouldn't work (not that you should change it because this is useless and won't be merged).

**Comment by Erisfiregamer1** [comment]
Ah, I see. I didn't see an Artifact so my mind assumed "ah they dont test the mod".

**Comment by seasnail8169** [comment]
why would we… our code is always perfect :trollface:

**Comment by seasnail8169** [comment]
https://app.circleci.com/pipelines/github/MeteorDevelopment/meteor-client

**Comment by seasnail8169** [comment]
Artifacts (we call them dev builds) can be downloaded as built from our discord server or also by fetching from [here](https://meteorclient.com/download?devBuild=latest)/

**Comment by seasnail8169** [comment]
https://discord.gg/metor

**Pull request closed without merging**
