### PR TITLE
Panic Module

### PR DESCRIPTION
**Pull request by Jaranamo1**
## Type of change

Adds Panic module

- [ ] Bug fix
- [x] New feature

## Description

Adds a module that can disable modules when a condition is met.
# It can:
- Disable modules on disconnect
- Disable modules if player in a certain distance (Optional exception for friends)
- Disable modules when a mob is in a certain distance

A summary of the changes along with the reasoning behind the changes.

- Added a new Panic.java file to the modules/misc directory
- Added the module to the Modules.java registry

## Related issues

Mention any issues that this pr relates to.

# How Has This Been Tested?

- This module has been tested on a server with other players.
- The code has been put through many edge cases and scenarios
- The logic has been reread many times

Videos or screenshots of the changes if applicable.

image

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by LemonsquizzerTHECOOL** [comment]
I like this.

**Comment by I-Got-You-Dead2** [comment]
This would literally only be used for cheating

**Comment by I-Got-You-Dead2** [comment]
Use .t all off or .panic in meteor rejects

**Comment by Jaranamo1** [comment]
I see this useful for when you want to swap to another server where you use different modules that is not a predefined config

**Comment by Talhoid** [comment]
> I see this useful for when you want to swap to another server where you use different modules that is not a predefined config

what

**Comment by Jaranamo1** [comment]
> > I see this useful for when you want to swap to another server where you use different modules that is not a predefined config
> 
> what

Makes disabling modules for new config easier

**Comment by GreemDev** [comment]
Yeah, let's add something that 99% of people are going to use to cheat, because it's literally called "Panic", just because you want a slightly faster way of making a new configuration

**Comment by Talhoid** [comment]
> > > I see this useful for when you want to swap to another server where you use different modules that is not a predefined config
> > 
> > 
> > what
> 
> Makes disabling modules for new config easier

still dont understnad what you mean, anyways rule 3

**Comment by I-Got-You-Dead2** [comment]
Goofy ass mfs

**Pull request closed without merging**
