### PR TITLE
The good old vanilla godmode.

### PR DESCRIPTION
**Pull request by ed0cinU**
It's kinda funny that this is working since mojang decided to add health into the game.

### CODE REVIEW

**Comment by Theboiboi8** [comment]
Very blatant.
Also, kinda mitigable and is not that useful.

**Comment by ed0cinU** [comment]
wtf

**Comment by ed0cinU** [comment]
sure

**Comment by wlwlwlmt91** [comment]
这有什么用

**Comment by BDARmech** [comment]
Det är en sköljning och upprepad sak.

**Pull request closed without merging**
