### PR TITLE
Add Slippy module

### PR DESCRIPTION
**Pull request by notnotnotswipez**
slippy slippery funny ice block haha

### CODE REVIEW

**Comment by notnotnotswipez** [comment]
As a better description: Makes blocks slippery with controllable slipperiness level and ignored blocks list

**Comment by ekcire06** [comment]
pog

**Comment by seasnail8169** [comment]
you should use setting.get().floatValue() to get a float from a setting.

**Comment by seasnail8169** [comment]
Also there is no need for the getSlippinessValue method at all, just make the setting public and get it like module.setting.get().floatValue()

**Comment by notnotnotswipez** [comment]
Noted, will address these changes soon :)

**Comment by seasnail8169** [comment]
Ping me when you have done so.

**Comment by notnotnotswipez** [comment]
@seasnail8169 Changes have been made

**Comment by notnotnotswipez** [comment]
Im sorry :waa:

**Pull request merged**
