### PR TITLE
Added powder Snow Bucket mode to No Fall

### PR DESCRIPTION
**Pull request by Hyped1XGeek**
Added a new mode to No Fall Module i.e. PowderSnow mode to mlg in Nether

### CODE REVIEW

**Comment by arlomcwalter** [comment]
just include it in Mode.bucket and check which dimension you are in

**Comment by Hyped1XGeek** [comment]
> just include it in Mode.bucket and check which dimension you are in

But someone might want it separately in cases like mlg on top half slab, top trapdoor, or stairs etc

In some cases when player has momentum it may fail to pick up water as soon as he lands so it may spread and may destroy some water-flushable blocks(like redstone

**Comment by arlomcwalter** [comment]
> > just include it in Mode.bucket and check which dimension you are in
> 
> 
> 
> why? maybe someone wants to use powdered snow in overworld
> 
> 

well sure but at least don't place water in the nether. the reasoning is that you wouldn't want to swap modes when you change dim. instead it could check if you have water and you aren't in the nether and place water and then if not it would look for other fallbacks like bales or snow or whatever. my point is, it would be good to provide some kind of automation so you don't have to reconfigure when you change dimension

**Comment by arlomcwalter** [comment]
> > just include it in Mode.bucket and check which dimension you are in
> 
> 
> 
> why? maybe someone wants to use powdered snow in overworld
> 
> 

well sure but at least don't place water in the nether. the reasoning is that you wouldn't want to swap modes when you change dim. instead it could check if you have water and you aren't in the nether and place water and then if not it would look for other fallbacks like bales or snow or whatever. my point is, it would be good to provide some kind of automation so you don't have to reconfigure when you change dimension

**Comment by arlomcwalter** [comment]
> > just include it in Mode.bucket and check which dimension you are in
> 
> 
> 
> But someone might want it separately in cases like mlg on top half slab, top trapdoor, or stairs etc
> 
> 
> 
> In some cases when player has momentum it may fail to pick up water as soon as he lands so it may spread and may destroy some water-flushable blocks(like redstone) 

could just add a check to see if the water is still there a few ticks later to make sure it is successful

**Comment by MineGame159** [comment]
@Hyped1XGeek are you gonna fix the code?

**Pull request closed without merging**
