### PR TITLE
Add meteor button to title screen

### PR DESCRIPTION
**Pull request by ThebestkillerTBK**

### CODE REVIEW

**Comment by MineGame159** [comment]
I don't like the idea of a Meteor button on title screen. @seasnail8169 wby

**Comment by ThebestkillerTBK** [comment]
> I don't like the idea of a Meteor button on title screen. @seasnail8169 wby

sometimes you have to turn off some modules

for example spam, get kicked, enter game, kicked again

**Comment by ThebestkillerTBK** [comment]
> You can open the gui in the main menu already, just press the gui button

wdym

**Comment by ThebestkillerTBK** [comment]
i found it 
its really secreat

**Pull request closed without merging**
