### PR TITLE
Use levenshtein distance for module searcher

### PR DESCRIPTION
**Pull request by StormyBytes**
Works better with typos and small inaccuracies. 
Perhaps the ins/del/sub costs may need to be tweaked, idk 1 3 5 worked good enough for me.

### CODE REVIEW

**Comment by MineGame159** [comment]
Wouldn't it be better to replace the current `Utils.search()` with some default costs?

**Comment by StormyBytes** [comment]
Should I change `Utils.search()` to utilize levenshtein and have it use some default costs? Kinda confused as to what you're saying.

**Comment by MineGame159** [comment]
Well thats what I am asking if it wouldn't be better. Isn't this supposed to be a generally better search algorithm?

**Comment by StormyBytes** [comment]
> Well thats what I am asking if it wouldn't be better. Isn't this supposed to be a generally better search algorithm?

Alright, levenshtein distance is now applied to other text search usages.

**Pull request merged**
