### PR TITLE
Sodium hotfix

### PR DESCRIPTION
**Pull request by RacoonDog**
## Type of change

- [X] Bug fix
- [ ] New feature

## Description

Sodium 0.4.11 was pulled from Modrinth by the CaffeineMC team and the currently Meteor is incompatible with the latest Sodium release. This pull request more or less reverts #3615 whilst keeping and improving upon the changes proposed in #3574

# How Has This Been Tested?

# Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have added comments to my code in more complex areas.
- [X] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by Wide-Cat** [comment]
Closes #3648

**Comment by I-Got-You-Dead2** [comment]
Wait what

**Comment by Soda5601** [comment]
so this just is a temporary workaround to make meteor compatible work with sodium 0.4.10, and has not fixed the problem itself

**Comment by RacoonDog** [comment]
> so this just is a temporary workaround to make meteor compatible work with sodium 0.4.10, and has not fixed the problem itself

there’s no “problem” per se, IMS of CaffeineMC pushed a new release with large unfinished changes to the API, so they pulled it when Jellysquid noticed

**Comment by BDARmech** [comment]
Umm, I dunno

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by RacoonDog** [comment]
In any case, since technically the 0.4.11 sodium that was pushed is “unfinished”, there is a good chance the real release will be different and won’t work with our current mixins

**Comment by RacoonDog** [comment]
(Also dont merge yet, I want to redo a mixin)

**Pull request merged**
