### PR TITLE
sendChatMessage event fix (Better Chat fix)

### PR DESCRIPTION
**Pull request by FurnyGo**
## Type of change

- [x] Bug fix

## Description

Fix sendChatMessage event baritone check

## Related issues

#4377 

# How Has This Been Tested?

Don't install baritone, run meteor and enable better chat prefix/suffix/fancy text function

# Checklist:

- [x] I have tested the code in both development and production environments.

### CODE REVIEW

**Comment by FurnyGo** [comment]
bump?

**Comment by FurnyGo** [comment]
@Wide-Cat can you check? This is literally 4 chars change in code

**Comment by Wide-Cat** [comment]
I'll test it this evening, but the boolean logic still doesn't look right to me. It's supposed to send the event if the message doesnt start with meteors prefix, and baritone is not available or it doesn't start with baritones prefix, right?

**Comment by Wide-Cat** [comment]
this doesnt work btw you cant use any of meteors commands anymore

**Comment by FurnyGo** [comment]
> It's supposed to send the event if the message doesnt start with meteors prefix, and baritone is not available or it doesn't start with baritones prefix, right?
It looked like this before the changes
If you change "or" to "and" and vice versa (as in pull request) everything works fine

**Comment by Wide-Cat** [comment]
Ok now it will only send the event if baritone is installed. Literally just read through the if statement in your head and see if it makes sense or not.

**Comment by FurnyGo** [comment]
I hope everything works fine now

**Pull request merged**
