### PR TITLE
Added a NoGlitchBlocks Module

### LINKED ISSUE #818: [Suggestion] Anti Ghost Blocks
**Describe the feature**
Anti ghost block.

### PR DESCRIPTION
**Pull request by vaxerski**
Fixes #818, IMHO.

This adds a module that will prevent ghost blocks from breaking stuff too fast. 

I've tested the recommended "Anti Ghost" mod on 9b9t (multiconnect 1.12.2) and it doesn't do anything. This, however, works perfectly.

It will prevent the client from removing the block until the server acknowledges the break. It will still play the breaking animations and sounds, because being silent it is annoying and confusing.

https://user-images.githubusercontent.com/43317083/196008001-fe04d9a0-3ed5-4997-a73b-c05343598daf.mp4

I am unsure about the name but that's how it's been called in my client and I took the name from future, so it should be pretty fitting.

### CODE REVIEW

**Comment by MineGame159** [comment]
Instead of adding the cancelled field manually make the event extend `Cancellable` class and call `INSTANCE.setCancelled(false);` inside the `BreakBlockEvent.get()` method and then `.cancel()` in the module.

**Comment by vaxerski** [comment]
done because I am still awake for some reason and this was an easy fix

**Comment by StormyBytes** [comment]
How about renaming it to "NoGhostBlocks"? Imo seems more fitting for the description "Attempts to prevent ghost blocks arising..."

**Comment by vaxerski** [comment]
> I am unsure about the name but that's how it's been called in my client and I took the name from future, so it should be pretty fitting.

I will leave any naming decisions to y'all, I really don't mind as long as it actually is intuitive.

**Pull request merged**
