### PR TITLE
Pause on Baritone now also works when not pathing for KillAura and BowAimbot

### PR DESCRIPTION
**Pull request by RedCarlos26**

### CODE REVIEW

**Comment by RedCarlos26** [comment]
Oops I think I forgot to update my gradle dependencies

**Comment by RedCarlos26** [comment]
Why is there apparently issues not even related to my code changes 🤔

**Comment by RedCarlos26** [comment]
Should I also rename the `wasPathing` variables to `wasBaritone` for more consistency?

**Comment by pwnker** [comment]
> Should I also rename the `wasPathing` variables to `wasBaritone` for more consistency, especially that now it doesn't pause only when pathing?

Yeah go for it.

**Comment by pwnker** [comment]
This can be merged, #2550 applies to these modules too.

**Review by pwnker — APPROVED** [review]
This can be merged, #2550 applies to these modules too.

**Comment by MineGame159** [comment]
Why tho

**Comment by RedCarlos26** [comment]
When using baritone to clear an area it's useful when it can actually pause to attack the entity then go back to work

**Comment by MineGame159** [comment]
Then the check should be improved instead of fully removing it.

**Comment by RedCarlos26** [comment]
Why improved? It's useless... Whtever try e process it we want to pause baritone when this is enabled like what?

**Comment by pwnker** [comment]
> Then the check should be improved instead of fully removing it.

Yeah thats valid if the check isn't useless. The check checks wether baritone is on and pathing but why would would it make a difference if you are pathing. You don't want to be swinging your pickaxe trying to use aura or autoeat. This PR is an extension of #2551.

**Comment by RedCarlos26** [comment]
@MineGame159 what do you mean by improving the check btw

**Pull request closed without merging**
