### PR TITLE
Fixed typos.

### PR DESCRIPTION
**Pull request by supakeks**

### CODE REVIEW

**Comment by seasnail8169** [comment]
no

**Comment by seasnail8169** [comment]
this is bullshit

**Comment by Columner** [comment]
broken english

**Comment by supakeks** [comment]
Dang alright I see how it is

**Comment by seasnail8169** [comment]
> broken english

as if your entire pr wasn’t broken english too lmao

**Comment by Columner** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
